update bash scripts

diff --git a/bin/boot b/bin/boot
--- a/bin/boot
+++ b/bin/boot
@@ -2,20 +2,31 @@
 set -euo pipefail
 
 #==============================================================#
-# File      :   meta.sh
+# File      :   boot
 # Ctime     :   2021-04-20
 # Mtime     :   2021-04-20
-# Desc      :   meta node bootstrap (install ansible)
+# Desc      :   boot meta node (use pkg.tgz and install ansible)
+# Usage     :   boot <pkg.tgz>
 # Note      :   run as root
 #               1. try unzip ./pkg.tgz as local repo first
 #               2. install ansible from local repo
 #               3. try install ansible from internet if not applicable
-# Path      :   files/meta.sh
+# Path      :   bin/boot
 # Copyright (C) 2018-2021 Ruohang Feng
 #==============================================================#
-
 PROG_NAME="$(basename $0))"
 PROG_DIR="$(cd $(dirname $0) && pwd)"
+PIGSTY_HOME="$(cd $(dirname ${PROG_DIR}) && pwd)"
+DEFAULT_PKG_PATH=${PIGSTY_HOME}/files/pkg.tgz
+
+function log_info() {
+    [[ -t 2 ]] && printf "\033[0;32m[$(date "+%Y-%m-%d %H:%M:%S")][$HOSTNAME][INFO] $*\033[0m\n" >&2 ||
+        printf "[$(date "+%Y-%m-%d %H:%M:%S")][$HOSTNAME][INFO] $*\n" >&2
+}
+function log_error() {
+    [[ -t 2 ]] && printf "\033[0;31m[$(date "+%Y-%m-%d %H:%M:%S")][$HOSTNAME][ERROR] $*\033[0m\n" >&2 ||
+        printf "[$(date "+%Y-%m-%d %H:%M:%S")][$HOSTNAME][INFO] $*\n" >&2
+}
 
 
 #==============================================================#
@@ -23,25 +34,22 @@ PROG_DIR="$(cd $(dirname $0) && pwd)"
 # Arg2      :   repo name (pigsty by default)
 # Arg3      :   repo home (/www by default)
 #==============================================================#
-DEFAULT_PKG_PATH=${PROG_DIR}/pkg.tgz
-
 PKG_PATH=${1-${DEFAULT_PKG_PATH}}
 REPO_NAME=${2-'pigsty'}
 REPO_HOME=${3-'/www'}
-
-echo "[INFO] extract ${PKG_PATH} to ${REPO_HOME}/${REPO_NAME}"
+log_info "extract ${PKG_PATH} to ${REPO_HOME}/${REPO_NAME}"
 
 # run this as root
 if [[ "$(whoami)" != "root" ]]; then
-    echo "[ERROR] permission denied: run this as root"
+    log_error "permission denied: run this as root"
     exit 1
 fi
 
 # check files/pkg.tgz exists
 if [[ -e ${PKG_PATH} ]]; then
-    echo "[INFO] ${PKG_PATH} exists"
+    log_info "${PKG_PATH} exists"
 else
-    echo "[ERROR] ${PKG_PATH} not exists, try boot from internet"
+    log_error "${PKG_PATH} not exists, try boot from internet"
     yum install -y createrepo sshpass wget yum yum-utils epel-release
     yum install -y ansible
     exit 0
@@ -49,29 +57,29 @@ fi
 
 # make sure repo home exists
 if [[ -d ${REPO_HOME} ]]; then
-    echo "[INFO] ${REPO_HOME} not found, create"
+    log_info "${REPO_HOME} not found, create"
     mkdir -p ${REPO_HOME}
 fi
 
 # make sure repo name dir not exists
 if [[ -d "${REPO_HOME}/${REPO_NAME}" ]]; then
-    echo "[WARN] ${REPO_HOME}/${REPO_NAME} exists, remove"
+    log_info "${REPO_HOME}/${REPO_NAME} exists, remove"
     rm -rf "${REPO_HOME:?}/${REPO_NAME:?}" "${REPO_HOME:?}/pigsty"
 fi
 
 # unzip pkg.tgz -> ${REPO_HOME}/pigsty
 tar -xf ${PKG_PATH} -C ${REPO_HOME}
 if [[ ${REPO_NAME} != "pigsty" ]]; then
-    echo "[INFO] move ${REPO_HOME}/pigsty to ${REPO_HOME}/${REPO_NAME}"
+    log_info "move ${REPO_HOME}/pigsty to ${REPO_HOME}/${REPO_NAME}"
 fi
 
 # backup all repos in /etc/yum.repos.d
-echo "[INFO] mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/"
+log_info "mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/"
 mkdir -p /etc/yum.repos.d/backup
 mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/ 2> /dev/null || true
 touch /etc/yum.repos.d/backup/${REPO_NAME}.repo
 
-echo "[INFO] create ${REPO_NAME}.repo"
+log_info "create ${REPO_NAME}.repo"
 cat >/etc/yum.repos.d/${REPO_NAME}.repo  <<-EOF
 [${REPO_NAME}]
 name=${REPO_NAME} \$releasever - \$basearch
@@ -80,11 +88,11 @@ enabled=1
 gpgcheck=0
 EOF
 
-echo "[INFO] remake yum cache"
+log_info "remake yum cache"
 yum clean all
 yum makecache
 
-echo "[INFO] install ansible utils"
+log_info "install ansible utils"
 yum install -y createrepo sshpass wget yum unzip yum-utils
 yum install -y ansible
 
