update binary scripts * pg_exporter v0.4.0 as default * use std logging utils instead of printf * add unzip to configure installed utils

diff --git a/bin/get_loki b/bin/get_loki
--- a/bin/get_loki
+++ b/bin/get_loki
@@ -4,13 +4,37 @@ set -euo pipefail
 #==============================================================#
 # File      :   get_loki
 # Ctime     :   2021-04-21
-# Mtime     :   2021-04-21
+# Mtime     :   2021-07-12
 # Desc      :   Get Loki Stuff from Github
 # Path      :   bin/get_loki
 # Depend    :   curl unzip
 # Copyright (C) 2018-2021 Ruohang Feng
 #==============================================================#
 
+#==============================================================#
+# color log util
+#==============================================================#
+__CN='\033[0m'    # no color
+__CB='\033[0;30m' # black
+__CR='\033[0;31m' # red
+__CG='\033[0;32m' # green
+__CY='\033[0;33m' # yellow
+__CB='\033[0;34m' # blue
+__CM='\033[0;35m' # magenta
+__CC='\033[0;36m' # cyan
+__CW='\033[0;37m' # white
+function log_info() {  printf "[${__CG} OK ${__CN}] ${__CG}$*${__CN}\n";   }
+function log_warn() {  printf "[${__CY}WARN${__CN}] ${__CY}$*${__CN}\n";   }
+function log_error() { printf "[${__CR}FAIL${__CN}] ${__CR}$*${__CN}\n";   }
+function log_debug() { printf "[${__CB}HINT${__CN}] ${__CB}$*${__CN}\n"; }
+function log_input() { printf "[${__CM} IN ${__CN}] ${__CM}$*\n=> ${__CN}"; }
+function log_hint()  { printf "${__CB}$*${__CN}\n"; }
+#==============================================================#
+
+
+#==============================================================#
+# download loki
+#==============================================================#
 function get_loki() {
     local tmpdir=/tmp
     local version=latest
@@ -36,116 +60,108 @@ function get_loki() {
 			    get_loki  -v 2.2.1        # get specific version of loki (2.2.1)
 			    get_loki  -p /usr/bin     # download binaries to specific path `/usr/bin`
 			    get_loki  -r              # force re-download and remove tarball after download
-
 			EOF
-			exit 0;;
+            exit 0;;
         -v|--version) version="$2" ; shift;;
         -p|--path) path="$2" ; shift;;
         -t|--tmpdir) tmpdir="$2" ; shift;;
         -r|--remove) remove="yes" ;;
         (--) shift; break;;
-        (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
+        (-*) log_error "$0: error - unrecognized option $1" 1>&2; exit 1;;
         (*) break;;
         esac
         shift
     done
 
-	# translate latest version into specific version with github API
-	if [[ ${version} == "latest" ]]; then
-		printf "\033[0;32m[INFO] get latest version of loki \033[0m\n" >&2
-		version=$(curl --silent "https://api.github.com/repos/grafana/loki/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
-		if [[ ${version} =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
-			printf "\033[0;32m[INFO] latest version of loki is v${version}\033[0m\n" >&2
-		else
-		    printf "\033[0;31m[INFO] fail to get latest loki version from github: $version \033[0m\n" >&2
-		    exit 1
-		fi
-	fi
+    # translate latest version into specific version with github API
+    if [[ ${version} == "latest" ]]; then
+        log_info "get latest version of loki"
+        version=$(curl --silent "https://api.github.com/repos/grafana/loki/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
+        if [[ ${version} =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
+            log_info "latest version of loki is v${version}"
+        else
+            log_error "fail to get latest loki version from github: $version"
+            exit 1
+        fi
+    fi
 
-	###################
-	# loki
-	##################
+    ###################
+    # loki
+    ##################
     local filename="loki-linux-amd64"
     local tarball="${filename}.zip"
     local url="https://github.com/grafana/loki/releases/download/v${version}/${tarball}"
-    printf "\033[0;32m[INFO] get loki binary v${version} to ${tmpdir} \033[0m\n" >&2
 
     if [[ ! -f ${tmpdir}/${tarball} || ${remove} == "yes" ]] ; then
-        printf "\033[0;32m[INFO] download binary ${tmpdir}/loki v${version} from ${url} to ${tmpdir} \033[0m\n" >&2
+        log_info "download loki from ${url} to ${tmpdir}"
         curl -L ${url} -o ${tmpdir}/${tarball}
     else
-        printf "\033[0;32m[INFO] found tarball on ${tmpdir}, extract to ${tmpdir}/${filename} \033[0m\n" >&2
+        log_hint "found loki on ${tmpdir}, move to ${path}/loki"
     fi
 
-    cd ${tmpdir}
+    cd ${tmpdir} > /dev/null
     rm -rf ${filename} && unzip -qq ${tarball} > /dev/null 2>&1 && mv -f ${filename} ${path}/loki
-    cd -
+    cd - > /dev/null
     [ ${remove} == "yes" ] && rm -rf ${tmpdir:?}/${tarball:?}    # remove tarball if -r|--remove specified
 
 
-	###################
-	# promtail
-	##################
+    ###################
+    # promtail
+    ##################
     local filename="promtail-linux-amd64"
     local tarball="${filename}.zip"
     local url="https://github.com/grafana/loki/releases/download/v${version}/${tarball}"
-    printf "\033[0;32m[INFO] get promtail binary v${version} to ${tmpdir} \033[0m\n" >&2
-
     if [[ ! -f ${tmpdir}/${tarball} || ${remove} == "yes" ]] ; then
-        printf "\033[0;32m[INFO] download binary ${tmpdir}/promtail v${version} from ${url} to ${tmpdir} \033[0m\n" >&2
+        log_info "download promtail from ${url} to ${tmpdir}"
         curl -L ${url} -o ${tmpdir}/${tarball}
     else
-        printf "\033[0;32m[INFO] found tarball on ${tmpdir}, extract to ${tmpdir}/${filename} \033[0m\n" >&2
+        log_hint "found promtail on ${tmpdir}, move to ${path}/loki"
     fi
-
-    cd ${tmpdir}
+    cd ${tmpdir} > /dev/null
     rm -rf ${filename} && unzip -qq ${tarball} && mv -f ${filename} ${path}/promtail
-    cd -
+    cd - > /dev/null
     [ ${remove} == "yes" ] && rm -rf ${tmpdir:?}/${tarball:?}    # remove tarball if -r|--remove specified
 
 
-	###################
-	# logcli
-	##################
+    ###################
+    # logcli
+    ##################
     local filename="logcli-linux-amd64"
     local tarball="${filename}.zip"
     local url="https://github.com/grafana/loki/releases/download/v${version}/${tarball}"
-    printf "\033[0;32m[INFO] get logcli binary v${version} to ${tmpdir} \033[0m\n" >&2
 
     if [[ ! -f ${tmpdir}/${tarball} || ${remove} == "yes" ]] ; then
-        printf "\033[0;32m[INFO] download binary ${tmpdir}/logcli v${version} from ${url} to ${tmpdir} \033[0m\n" >&2
+        log_info "download logcli from ${url} to ${tmpdir}"
         curl -L ${url} -o ${tmpdir}/${tarball}
     else
-        printf "\033[0;32m[INFO] found tarball on ${tmpdir}, extract to ${tmpdir}/${filename} \033[0m\n" >&2
+        log_hint "found logcli on ${tmpdir}, move to ${path}/loki"
     fi
 
-    cd ${tmpdir}
+    cd ${tmpdir} > /dev/null
     rm -rf ${filename} && unzip -qq ${tarball} && mv -f ${filename} ${path}/logcli
-    cd -
+    cd - > /dev/null
     [ ${remove} == "yes" ] && rm -rf ${tmpdir:?}/${tarball:?}    # remove tarball if -r|--remove specified
 
-	###################
-	# loki-canary
-	##################
+    ###################
+    # loki-canary
+    ##################
     local filename="loki-canary-linux-amd64"
     local tarball="${filename}.zip"
     local url="https://github.com/grafana/loki/releases/download/v${version}/${tarball}"
-    printf "\033[0;32m[INFO] get loki-canary binary v${version} to ${tmpdir} \033[0m\n" >&2
 
     if [[ ! -f ${tmpdir}/${tarball} || ${remove} == "yes" ]] ; then
-        printf "\033[0;32m[INFO] download binary ${tmpdir}/loki-canary v${version} from ${url} to ${tmpdir} \033[0m\n" >&2
+        log_info "download loki-canary from ${url} to ${tmpdir}"
         curl -L ${url} -o ${tmpdir}/${tarball}
     else
-        printf "\033[0;32m[INFO] found tarball on ${tmpdir}, extract to ${tmpdir}/${filename} \033[0m\n" >&2
+        log_hint "found loki-canary on ${tmpdir}, move to ${path}/loki"
     fi
 
-    cd ${tmpdir}
+    cd ${tmpdir} > /dev/null
     rm -rf ${filename} && unzip -qq ${tarball} && mv -f ${filename} ${path}/loki-canary
-    cd -
+    cd - > /dev/null
     [ ${remove} == "yes" ] && rm -rf ${tmpdir:?}/${tarball:?}    # remove tarball if -r|--remove specified
 
-
-    printf "\033[0;32m[INFO] ${path} \033[0m\n" >&2
+    log_info "loki @ ${path}"
 }
 
 get_loki $@
diff --git a/bin/get_node_exporter b/bin/get_node_exporter
--- a/bin/get_node_exporter
+++ b/bin/get_node_exporter
@@ -4,11 +4,39 @@ set -euo pipefail
 #==============================================================#
 # File      :   get_node_exporter
 # Ctime     :   2021-04-21
-# Mtime     :   2021-04-21
+# Mtime     :   2021-07-12
 # Desc      :   Get Node Exporter From Github Release
 # Path      :   bin/get_node_exporter
 # Depend    :   curl
 # Copyright (C) 2018-2021 Ruohang Feng
+#==============================================================#
+
+# color log util
+__CN='\033[0m'    # no color
+__CB='\033[0;30m' # black
+__CG='\033[0;32m' # green
+function log_info() {  printf "[${__CG} OK ${__CN}] ${__CG}$*${__CN}\n";   }
+function log_hint()  { printf "${__CB}$*${__CN}\n"; }
+
+
+#==============================================================#
+# color log util
+#==============================================================#
+__CN='\033[0m'    # no color
+__CB='\033[0;30m' # black
+__CR='\033[0;31m' # red
+__CG='\033[0;32m' # green
+__CY='\033[0;33m' # yellow
+__CB='\033[0;34m' # blue
+__CM='\033[0;35m' # magenta
+__CC='\033[0;36m' # cyan
+__CW='\033[0;37m' # white
+function log_info() {  printf "[${__CG} OK ${__CN}] ${__CG}$*${__CN}\n";   }
+function log_warn() {  printf "[${__CY}WARN${__CN}] ${__CY}$*${__CN}\n";   }
+function log_error() { printf "[${__CR}FAIL${__CN}] ${__CR}$*${__CN}\n";   }
+function log_debug() { printf "[${__CB}HINT${__CN}] ${__CB}$*${__CN}\n"; }
+function log_input() { printf "[${__CM} IN ${__CN}] ${__CM}$*\n=> ${__CN}"; }
+function log_hint()  { printf "${__CB}$*${__CN}\n"; }
 #==============================================================#
 
 function get_node_exporter() {
@@ -43,7 +71,7 @@ function get_node_exporter() {
         -t|--tmpdir) tmpdir="$2" ; shift;;
         -r|--remove) remove="yes" ;;
         (--) shift; break;;
-        (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
+        (-*) log_error "$0: error - unrecognized option $1"; exit 1;;
         (*) break;;
         esac
         shift
@@ -51,12 +79,12 @@ function get_node_exporter() {
 
 	# translate latest version into specific version with github API
 	if [[ ${version} == "latest" ]]; then
-		printf "\033[0;32m[INFO] get latest version of node_exporter \033[0m\n" >&2
+		log_info "get latest version of node_exporter"
 		version=$(curl --silent "https://api.github.com/repos/prometheus/node_exporter/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
 		if [[ ${version} =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
-			printf "\033[0;32m[INFO] latest version of node_exporter is v${version}\033[0m\n" >&2
+			log_info "latest version of node_exporter is v${version}"
 		else
-		    printf "\033[0;31m[INFO] fail to get latest node_exporter version from github: $version \033[0m\n" >&2
+		    log_error "fail to get latest node_exporter version from github: $version"
 		    exit 1
 		fi
 	fi
@@ -65,19 +93,17 @@ function get_node_exporter() {
     local tarball="${filename}.tar.gz"
     local url="https://github.com/prometheus/node_exporter/releases/download/v${version}/${tarball}"
 
-    printf "\033[0;32m[INFO] get node_exporter binary v${version} to ${tmpdir} \033[0m\n" >&2
     if [[ ! -f ${tmpdir}/${tarball} || ${remove} == "yes" ]] ; then
-        printf "\033[0;32m[INFO] download binary ${tmpdir}/node_exporter v${version} from ${url} to ${tmpdir} \033[0m\n" >&2
+        log_info "download node_exporter v${version} from ${url} to ${tmpdir}"
         curl -L ${url} -o ${tmpdir}/${tarball}
     else
-        printf "\033[0;32m[INFO] found tarball on ${tmpdir}, extract to ${tmpdir}/${filename} \033[0m\n" >&2
+    	log_hint "found tarball on ${tmpdir}, extract to ${path}"
     fi
 
     tar -xf ${tmpdir}/${tarball} -C ${tmpdir}
     mv -f "${tmpdir}/${filename}/node_exporter" ${path}
     rm -rf ${tmpdir:?}/${filename:?}                             # remove dir
     [ ${remove} == "yes" ] && rm -rf ${tmpdir:?}/${tarball:?}    # remove tarball if -r|--remove specified
-    printf "\033[0;32m[INFO] ${path} \033[0m\n" >&2
 }
 
 get_node_exporter $@
