fix bin scripts * add createpg wrapper

diff --git a/bin/load_log b/bin/load_log
--- a/bin/load_log
+++ b/bin/load_log
@@ -27,6 +27,10 @@ LOG_PATH=${1}
 # known issues:
 # * csvlog below PG 13 does not have backend_type field
 # * +8 Timezone CST will be parse as -6
+if [[ -z "${LOG_PATH}" ]]; then
+	echo "invalid log path ${1}"
+	exit 1
+fi
 
 #==============================================================#
 # load log
