rename bin/pg-* scripts to bin/pgsql-*

diff --git a/bin/pgsql-add b/bin/pgsql-add
--- a/bin/pgsql-add
+++ b/bin/pgsql-add
@@ -1,11 +1,11 @@
 #!/bin/bash
 set -uo pipefail
 #==============================================================#
-# File      :   pg-add
+# File      :   pgsql-add
 # Desc      :   Create PostgreSQL Cluster / Append Replicas
 # Ctime     :   2021-07-15
 # Mtime     :   2022-12-28
-# Path      :   bin/pg-add
+# Path      :   bin/pgsql-add
 # Deps      :   ansible-playbook, pgsql.yml
 # Author    :   Ruohang Feng (rh@vonng.com)
 # License   :   AGPLv3
@@ -18,8 +18,8 @@ PIGSTY_HOME=$(cd $(dirname ${APP_DIR}) && pwd)
 #--------------------------------------------------------------#
 # Usage
 #--------------------------------------------------------------#
-# bin/pg-add <cls>          # create pgsql cluster 'cls'
-# bin/pg-add <cls> [ip...]  # add replicas to cluster
+# bin/pgsql-add <cls>          # create pgsql cluster 'cls'
+# bin/pgsql-add <cls> [ip...]  # add replicas to cluster
 
 #--------------------------------------------------------------#
 # Utils
@@ -49,8 +49,8 @@ PG_CLUSTER=${1-''}
 if [[ -z "${PG_CLUSTER}" ]]; then
 	log_error "pg_cluster is empty"
 	log_hint "Usage:"
-	log_hint "    bin/pg-add <cls>          # create pgsql cluster 'cls'"
-	log_hint "    bin/pg-add <cls> [ip...]  # add replicas to cluster"
+	log_hint "    bin/pgsql-add <cls>          # create pgsql cluster 'cls'"
+	log_hint "    bin/pgsql-add <cls> [ip...]  # add replicas to cluster"
 	exit 1
 fi
 
@@ -61,22 +61,26 @@ fi
 # if only 1 arg is given, arg1 = pg_cluster
 # the entire pgsql cluster will be created
 if (($# == 1)); then
-	log_line "SUMMARY"
+	log_line "PLANNING"
 	log_warn "create pgsql cluster '${PG_CLUSTER}'"
   log_warn "please make sure nodes are added to pigsty"
-  log_hint "[HINT] did you run:  ./node.yml -l ${PG_CLUSTER}  ahead?"
+  log_hint "[HINT] did you run:  bin/node-add ${PG_CLUSTER}  ahead?"
 
 	log_line "EXECUTE"
 	log_info "create pgsql cluster '${PG_CLUSTER}' begin"
 	log_hint "$ ./pgsql.yml" -l "${PG_CLUSTER}"
+
 	"${PIGSTY_HOME}/pgsql.yml" -l "${PG_CLUSTER}"
-	RETURN_CODE=$?
+
+  if [[ $? -ne 0 ]]; then
+    log_line "FAILURE"
+    log_error "fail to create pgsql cluster for '${PG_CLUSTER}'"
+    exit 2
+  fi
+  log_line "SUMMARY"
 	log_info "create pgsql cluster ${PG_CLUSTER} complete!"
-
-	log_line "POSTRUN"
-	log_hint "conn check: psql postgres://${PG_CLUSTER}/postgres"
-
-	exit ${RETURN_CODE}
+  log_hint "conn check: psql postgres://${PG_CLUSTER}/postgres"
+	exit 0
 fi
 
 
@@ -93,42 +97,67 @@ for ((i=2; i<=$#; i++))
 do
   if ! is_valid_ip "${!i}"; then
     log_error "invalid ip address given: ${!i}"
-    exit 1
+    exit 3
   fi
   IP_LIST="${IP_LIST} ${!i}"
   TARGET_PATTERN="${!i},${TARGET_PATTERN}"
   EXISTS_PATTERN="${EXISTS_PATTERN},!${!i}"
 done
 
+#---------------------------------#
 # Planning
-log_line "SUMMARY"
-log_info "add instances ${IP_LIST} to pgsql cluster '${PG_CLUSTER}':"
+#---------------------------------#
+log_line "PLANNING"
+log_info "init instances ${IP_LIST} to pgsql cluster '${PG_CLUSTER}':"
 log_warn "  reminder: did you add nodes to pigsty?     # infra nodes were added"
-log_hint "[HINT]     # ./node.yml  -l '${TARGET_PATTERN}'  # run this before pg-add"
+log_hint "[HINT]     # bin/node.yml  -l '${TARGET_PATTERN}'  # run this before pgsql-add"
 log_warn "  init instances from cluster:"
 log_info "    $ ./pgsql.yml -l '${TARGET_PATTERN}'"
 log_warn "  reload pg_service on existing instances:"
 log_info "    $ ./pgsql.yml -l '${EXISTS_PATTERN}' -t pg_service"
 
+#---------------------------------#
 # Init Instances
+#---------------------------------#
 log_line "EXECUTE"
-log_warn "add instances ${IP_LIST}  to ${PG_CLUSTER}"
+log_warn "init instances  ${IP_LIST}  of ${PG_CLUSTER}"
 log_hint "$ ./pgsql.yml -l '${TARGET_PATTERN}'"
+
 "${PIGSTY_HOME}/pgsql.yml" -l "${TARGET_PATTERN}"
 
-# Reload Services
-log_line "EXECUTE"
-# TODO: if you are init a primary of cluster, this is not actually necessary
-log_warn "reload pg_service on existing ${PG_CLUSTER} members"
-log_hint "$ ./pgsql.yml -l '${EXISTS_PATTERN}' -t pg_service"
-"${PIGSTY_HOME}/pgsql.yml" -l "${EXISTS_PATTERN}" -t pg_service ;
+if [[ $? -ne 0 ]]; then
+  log_line "FAILURE"
+  log_error "fail to init pgsql instance for ${IP_LIST} of ${PG_CLUSTER}"
+  exit 4
+fi
+log_info "init pgsql instance for ${IP_LIST} of ${PG_CLUSTER} complete"
 
-# Print Info
-log_line "POSTRUN"
-log_info "add pgsql instances ${IP_LIST} to '${PG_CLUSTER}' complete"
+#---------------------------------#
+# Reload Services
+#---------------------------------#
+# TODO: if you are init a primary of cluster, this is not actually necessary
+log_line "EXECUTE"
+log_warn "reload pgsql services on ${EXISTS_PATTERN}"
+log_hint "$ ./pgsql.yml -l '${EXISTS_PATTERN}' -t pg_service"
+
+"${PIGSTY_HOME}/pgsql.yml" -l "${EXISTS_PATTERN}" -t pg_service
+
+if [[ $? -ne 0 ]]; then
+  log_line "FAILURE"
+  log_error "fail to reload pgsql services on ${EXISTS_PATTERN}"
+  log_warn "current traffic may not be affected immediately"
+  log_warn "BUT IT'S VERY IMPORTANT TO FIX THIS ASAP!"
+  exit 5
+fi
+log_info "reload pgsql services for ${IP_LIST} of ${PG_CLUSTER} complete"
+
+#---------------------------------#
+# Summary
+#---------------------------------#
+log_line "SUMMARY"
+log_info "init pgsql instance ${IP_LIST} of ${PG_CLUSTER} success"
 for ((i=2; i<=$#; i++))
 do
   log_hint "conn check: psql postgres://${!i}/postgres"
 done
-
 exit 0
diff --git a/bin/pgsql-db b/bin/pgsql-db
--- a/bin/pgsql-db
+++ b/bin/pgsql-db
@@ -1,12 +1,12 @@
 #!/bin/bash
 set -uo pipefail
 #==============================================================#
-# File      :   pg-user
-# Desc      :   Create PostgreSQL Business USer
+# File      :   pgsql-db
+# Desc      :   Create database on postgres cluster
 # Ctime     :   2021-07-15
 # Mtime     :   2022-12-28
-# Path      :   bin/pg-user
-# Deps      :   ansible-playbook, pgsql-user.yml
+# Path      :   bin/pgsql-db
+# Deps      :   ansible-playbook, pgsql-db.yml
 # Author    :   Ruohang Feng (rh@vonng.com)
 # License   :   AGPLv3
 #==============================================================#
@@ -18,8 +18,8 @@ PIGSTY_HOME=$(cd $(dirname ${APP_DIR}) && pwd)
 #--------------------------------------------------------------#
 # Usage
 #--------------------------------------------------------------#
-# bin/pg-user <cls> <username>  # define user in inventory first
-# `app.children.<cls>.vars.pg_users`, entry with name=<username>
+# bin/pgsql-db <cluster> <dbname>  # define database in inventory first
+# `app.children.<cluster>.vars.pg_databases`, entry with name=<dbname>
 
 
 #--------------------------------------------------------------#
@@ -35,23 +35,27 @@ function log_input() { printf "[${__CM} IN ${__CN}] ${__CM}$*\n=> ${__CN}"; }
 function log_hint()  { printf "${__CB}$*${__CN}\n"; }
 function log_line()  { printf "${__CM}[$*] ===========================================${__CN}\n"; }
 
+
+
 #--------------------------------------------------------------#
 # Param
 #--------------------------------------------------------------#
 PG_CLUSTER=${1-''}
-USERNAME=${2-''}
+DBNAME=${2-''}
 
 if [[ -z "${PG_CLUSTER}" ]]; then
     log_error "pg_cluster is empty"
     log_hint "Usage:"
-    log_hint "    bin/pg-user <cls> <username>"
+    log_hint "    bin/pgsql-db <cls> <dbname>"
     exit 1
 fi
-if [[ -z "${USERNAME}" ]]; then
-    log_error "username is empty"
-    log_warn "don't forget to define user in  all.children.${PG_CLUSTER}.vars.pg_users  first"
+if [[ -z "${DBNAME}" ]]; then
+    log_error "dbname is empty"
     log_hint "Usage:"
-    log_hint "    bin/pg-user <cls> <username>"
+    log_hint "    bin/pgsql-db <cls> <dbname>"
+
+    log_warn "don't forget to define database in  all.children.${PG_CLUSTER}.vars.pg_databases  first"
+    log_warn "if database have owner, make sure the user already exists, or create it with pg-user first"
     exit 2
 fi
 
@@ -60,17 +64,17 @@ fi
 # Execute
 #--------------------------------------------------------------#
 log_line "EXECUTE"
-log_warn "create pg user '${USERNAME}' on '${PG_CLUSTER}'"
-log_hint "$ ./pgsql-user.yml -l ${PG_CLUSTER} -e username=${USERNAME}"
-"${PIGSTY_HOME}/pgsql-user.yml" -l "${PG_CLUSTER}" -e username="${USERNAME}"
-RETURN_CODE=$?
+log_warn "create pgsql database '${DBNAME}' on '${PG_CLUSTER}'"
+log_hint "$ ./pgsql-db.yml -l ${PG_CLUSTER} -e dbname=${DBNAME}"
 
-log_line "SUMMARY"
-if [[ ${RETURN_CODE} -eq 0 ]]; then
-  log_info "create pg user ${USERNAME} on '${PG_CLUSTER}' complete"
-  log_hint "check pgurl: postgres://${USERNAME}:<PASSWORD>@${PG_CLUSTER}/postgres"
-  exit 0
-else
-  log_error "fail to create pg user ${USERNAME} on '${PG_CLUSTER}'"
+"${PIGSTY_HOME}/pgsql-db.yml" -l "${PG_CLUSTER}" -e dbname="${DBNAME}"
+
+if [[ $? -ne 0 ]]; then
+  log_line "FAILURE"
+  log_error "fail to create pgsql database on '${PG_CLUSTER}'"
   exit 3
 fi
+log_line "SUMMARY"
+log_info "create pgsql database ${DBNAME} on '${PG_CLUSTER}' complete"
+log_hint "check pgurl: postgres://${PG_CLUSTER}/${DBNAME}"
+exit 0
diff --git a/bin/pgsql-hba b/bin/pgsql-hba
--- a/bin/pgsql-hba
+++ b/bin/pgsql-hba
@@ -1,12 +1,12 @@
 #!/bin/bash
 set -uo pipefail
 #==============================================================#
-# File      :   pg-rm
-# Desc      :   Remove PostgreSQL Cluster / Remove Replicas
-# Ctime     :   2022-12-28
+# File      :   pgsql-hba
+# Desc      :   Refresh Postgres/Pgbouncer HBA Rules
+# Ctime     :   2021-11-02
 # Mtime     :   2022-12-28
-# Path      :   bin/pg-rm
-# Deps      :   ansible-playbook, pgsql.yml, pgsql-rm.yml
+# Path      :   bin/pgsql-hba
+# Deps      :   ansible-playbook, pgsql.yml
 # Author    :   Ruohang Feng (rh@vonng.com)
 # License   :   AGPLv3
 #==============================================================#
@@ -18,8 +18,8 @@ PIGSTY_HOME=$(cd $(dirname ${APP_DIR}) && pwd)
 #--------------------------------------------------------------#
 # Usage
 #--------------------------------------------------------------#
-# bin/pg-rm <cls>          # remove entire cluster 'cls'
-# bin/pg-rm <cls> [ip...]  # remove replicas from cluster
+# bin/pgsql-hba <cls>          # refresh hba rules for cluster 'cls'
+# bin/pgsql-hba <cls> [ip...]  # refresh hba rules for specific instances
 
 
 #--------------------------------------------------------------#
@@ -42,7 +42,6 @@ function is_valid_ip(){
     fi
 }
 
-
 #--------------------------------------------------------------#
 # Param
 #--------------------------------------------------------------#
@@ -50,42 +49,46 @@ PG_CLUSTER=${1-''}
 if [[ -z "${PG_CLUSTER}" ]]; then
 	log_error "pg_cluster is empty"
 	log_hint "Usage:"
-	log_hint "    bin/pg-rm <cls>          # remove entire cluster 'cls'"
-	log_hint "    bin/pg-rm <cls> [ip...]  # remove instances from cluster"
+	log_hint "    bin/pgsql-hba <cls>          # refresh pg/pgb hba rules for cluster 'cls'"
+	log_hint "    bin/pgsql-hba <cls> [ip...]  # refresh pg/pgb hba rules for specific instances"
 	exit 1
 fi
 
 
 #--------------------------------------------------------------#
-# Destroy Cluster                    [ 1 arg = destroy cluster ]
+# Reload Cluster HBA                  [ 1 arg = reload cls hba ]
 #--------------------------------------------------------------#
 # if only 1 arg is given, arg1 = pg_cluster
-# the entire pgsql cluster will be removed
+# hba rules of the entire pgsql cluster will be reloaded
 if (($# == 1)); then
-	log_line "SUMMARY"
-	log_warn "remove pgsql cluster '${PG_CLUSTER}'"
-
 	log_line "EXECUTE"
-	log_hint "$ ./pgsql-rm.yml" -l "${PG_CLUSTER}"
-	"${PIGSTY_HOME}/pgsql-rm.yml" -l "${PG_CLUSTER}"
+	log_warn "reload hba rules for '${PG_CLUSTER}'"
+  log_hint "$ ./pgsql.yml -l '${PG_CLUSTER}' -t pg_hba"
+  "${PIGSTY_HOME}/pgsql.yml" -l "${PG_CLUSTER}" -t pg_hba
 	RETURN_CODE=$?
-	log_info "remove pgsql cluster ${PG_CLUSTER} complete!"
 
-	log_line "POSTRUN"
-	log_warn "please adjust your inventory accordingly"
-	log_hint "remove '${PG_CLUSTER}' from inventory: all.children"
-  log_warn "nodes will not be removed from pigsty, to do so:"
-  log_hint "$ ./node-rm.yml -l '${PG_CLUSTER}'"
+  log_line "SUMMARY"
+  if [[ ${RETURN_CODE} -eq 0 ]]; then
+    log_info "reload hba rules for '${PG_CLUSTER}' complete"
+    exit 0
+  else
+    log_error "fail to reload hba rules for '${PG_CLUSTER}'"
+    log_warn "current traffic may not be affected immediately"
+    log_warn "BUT IT'S VERY IMPORTANT TO FIX THIS ASAP!"
+    exit 2
+  fi
+
+	log_info "reload pgsql hba rules for ${PG_CLUSTER} complete!"
 	exit ${RETURN_CODE}
 fi
 
 
+
 #--------------------------------------------------------------#
-# Remove Instances                 [2+ args = remove instances ]
+# Reload Specific Instances           [2+ args = reload ins hba]
 #--------------------------------------------------------------#
 # if more than 1 args is given, arg1 = pg_cluster, arg2+ = ip list
-# each instance (with corresponding ip) will be removed from pg_cluster
-# haproxy on existing instances will be reloaded to re-route traffic
+# each instance (with corresponding ip) hba rules will be reloaded
 IP_LIST=""
 TARGET_PATTERN="&${PG_CLUSTER}"
 EXISTS_PATTERN="${PG_CLUSTER}"
@@ -93,40 +96,27 @@ for ((i=2; i<=$#; i++))
 do
   if ! is_valid_ip "${!i}"; then
     log_error "invalid ip address given: ${!i}"
-    exit 1
+    exit 3
   fi
   IP_LIST="${IP_LIST} ${!i}"
   TARGET_PATTERN="${!i},${TARGET_PATTERN}"
   EXISTS_PATTERN="${EXISTS_PATTERN},!${!i}"
 done
 
-# Planning
+# Reload Postgres HBA
+log_line "EXECUTE"
+log_warn "reload hba rules on specific ${PG_CLUSTER} members"
+log_hint "$ ./pgsql.yml -l '${TARGET_PATTERN}' -t pg_hba"
+"${PIGSTY_HOME}/pgsql.yml" -l "${TARGET_PATTERN}" -t pg_hba,pgbouncer_hba,pgbouncer_reload
+RETURN_CODE=$?
+
 log_line "SUMMARY"
-log_info "remove instances ${IP_LIST} from pgsql cluster '${PG_CLUSTER}':"
-log_warn "  remove instances from cluster:"
-log_info "    $ ./pgsql-rm.yml -l '${TARGET_PATTERN}'"
-log_warn "  reload pg_service on existing instances:"
-log_info "    $ ./pgsql.yml -l '${EXISTS_PATTERN}' -t pg_service"
-
-
-# Remove Instances
-log_line "EXECUTE"
-log_warn "remove instance ${IP_LIST} from ${PG_CLUSTER}"
-log_hint "$ ./pgsql-rm.yml -l '${TARGET_PATTERN}'"
-"${PIGSTY_HOME}/pgsql-rm.yml" -l "${TARGET_PATTERN}"
-
-# Reload Services
-log_line "EXECUTE"
-log_warn "reload pg_service on existing ${PG_CLUSTER} members"
-log_hint "$ ./pgsql.yml -l '${EXISTS_PATTERN}' -t pg_service"
-"${PIGSTY_HOME}/pgsql.yml" -l "${EXISTS_PATTERN}" -t pg_service
-log_info "remove pgsql instances ${IP_LIST} from '${PG_CLUSTER}' complete"
-
-# Print Info
-log_line "POSTRUN"
-log_warn "please adjust your inventory accordingly"
-log_hint "remove ${IP_LIST}  from inventory: all.children.${PG_CLUSTER}.hosts"
-log_warn "nodes will not be removed from pigsty, to do so:"
-log_hint "$ ./node-rm.yml -l ${IP_LIST}"
-
-exit 0
+if [[ ${RETURN_CODE} -eq 0 ]]; then
+  log_info "reload hba rules for ${IP_LIST} of ${PG_CLUSTER }complete"
+  exit 0
+else
+  log_error "fail to reload hba rules for ${IP_LIST} of ${PG_CLUSTER}"
+  log_warn "current traffic may not be affected immediately"
+  log_warn "BUT IT'S VERY IMPORTANT TO FIX THIS ASAP!"
+  exit 4
+fi
diff --git a/bin/pgsql-svc b/bin/pgsql-svc
--- a/bin/pgsql-svc
+++ b/bin/pgsql-svc
@@ -1,11 +1,11 @@
 #!/bin/bash
-set -euo pipefail
+set -uo pipefail
 #==============================================================#
-# File      :   pg-hba
-# Desc      :   Refresh Postgres Cluster HBA Rules
-# Ctime     :   2021-11-02
+# File      :   pgsql-svc
+# Desc      :   Refresh PGSQL Cluster Services on HAProxy
+# Ctime     :   2021-12-03
 # Mtime     :   2022-12-28
-# Path      :   bin/pg-hba
+# Path      :   bin/pgsql-svc
 # Deps      :   ansible-playbook, pgsql.yml
 # Author    :   Ruohang Feng (rh@vonng.com)
 # License   :   AGPLv3
@@ -18,8 +18,8 @@ PIGSTY_HOME=$(cd $(dirname ${APP_DIR}) && pwd)
 #--------------------------------------------------------------#
 # Usage
 #--------------------------------------------------------------#
-# bin/pg-hba <cls>          # refresh postgres hba rules for cluster 'cls'
-# bin/pg-hba <cls> [ip...]  # refresh postgres hba rules for specific instances
+# bin/pgsql-svc <cls>          # refresh haproxy services of cluster 'cls'
+# bin/pgsql-svc <cls> [ip...]  # refresh services on specific instances
 
 
 #--------------------------------------------------------------#
@@ -49,34 +49,42 @@ PG_CLUSTER=${1-''}
 if [[ -z "${PG_CLUSTER}" ]]; then
 	log_error "pg_cluster is empty"
 	log_hint "Usage:"
-	log_hint "    bin/pg-hba <cls>          # refresh postgres hba rules for cluster 'cls'"
-	log_hint "    bin/pg-hba <cls> [ip...]  # refresh postgres hba rules for specific instances"
+	log_hint "    bin/pgsql-svc <cls>          # refresh haproxy services of cluster 'cls'"
+	log_hint "    bin/pgsql-svc <cls> [ip...]  # refresh services on specific instances"
 	exit 1
 fi
 
 
 #--------------------------------------------------------------#
-# Reload Cluster HBA                  [ 1 arg = reload cls hba ]
+# Create Cluster                     [ 1 arg = refresh cluster ]
 #--------------------------------------------------------------#
 # if only 1 arg is given, arg1 = pg_cluster
-# hba rules of the entire pgsql cluster will be reloaded
+# the entire pgsql cluster will be refreshed
 if (($# == 1)); then
 	log_line "EXECUTE"
-	log_warn "reload postgres hba rules for '${PG_CLUSTER}'"
-  log_hint "$ ./pgsql.yml -l '${PG_CLUSTER}' -t pg_hba"
-  "${PIGSTY_HOME}/pgsql.yml" -l "${PG_CLUSTER}" -t pg_hba
-	RETURN_CODE=$?
-	log_info "reload pgsql hba rules for ${PG_CLUSTER} complete!"
-	exit ${RETURN_CODE}
+	log_warn "reload pgsql services for '${PG_CLUSTER}'"
+  log_hint "$ ./pgsql.yml -l '${PG_CLUSTER}' -t pg_service"
+
+  "${PIGSTY_HOME}/pgsql.yml" -l "${PG_CLUSTER}" -t pg_service
+
+  if [[ $? -ne 0 ]]; then
+    log_line "FAILURE"
+    log_error "fail to reload pgsql services for '${PG_CLUSTER}'"
+    exit 2
+  fi
+  log_line "SUMMARY"
+	log_info "reload pgsql services for ${PG_CLUSTER} complete!"
+  log_hint "check haproxy admin page: http://h.pigsty/${PG_CLUSTER}-n/"
+	exit 0
 fi
 
 
 
 #--------------------------------------------------------------#
-# Reload Specific Instances           [2+ args = reload ins hba]
+# Refresh Specific Instances       [2+ args = refresh instances]
 #--------------------------------------------------------------#
 # if more than 1 args is given, arg1 = pg_cluster, arg2+ = ip list
-# each instance (with corresponding ip) hba rules will be reloaded
+# each instance (with corresponding ip) haproxy will be refreshed
 IP_LIST=""
 TARGET_PATTERN="&${PG_CLUSTER}"
 EXISTS_PATTERN="${PG_CLUSTER}"
@@ -84,17 +92,28 @@ for ((i=2; i<=$#; i++))
 do
   if ! is_valid_ip "${!i}"; then
     log_error "invalid ip address given: ${!i}"
-    exit 1
+    exit 3
   fi
   IP_LIST="${IP_LIST} ${!i}"
   TARGET_PATTERN="${!i},${TARGET_PATTERN}"
   EXISTS_PATTERN="${EXISTS_PATTERN},!${!i}"
 done
 
-# Reload Postgres HBA
+# Reload Services
 log_line "EXECUTE"
-log_warn "reload postgres hba rules on specific ${PG_CLUSTER} members"
-log_hint "$ ./pgsql.yml -l '${TARGET_PATTERN}' -t pg_hba"
-"${PIGSTY_HOME}/pgsql.yml" -l "${TARGET_PATTERN}" -t pg_hba
+log_warn "reload pgsql services on specific ${PG_CLUSTER} members"
+log_hint "$ ./pgsql.yml -l '${TARGET_PATTERN}' -t pg_service"
 
+"${PIGSTY_HOME}/pgsql.yml" -l "${TARGET_PATTERN}" -t pg_service
+
+if [[ $? -ne 0 ]]; then
+  log_line "FAILURE"
+  log_error "fail to reload pgsql services for '${PG_CLUSTER}'"
+  log_warn "current traffic may not be affected immediately"
+  log_warn "BUT IT'S VERY IMPORTANT TO FIX THIS ASAP!"
+  exit 4
+fi
+log_line "SUMMARY"
+log_info "reload pgsql services for ${IP_LIST} of ${PG_CLUSTER} complete"
+log_hint "check haproxy admin page: http://h.pigsty/${PG_CLUSTER}-n/"
 exit 0
diff --git a/bin/pgsql-user b/bin/pgsql-user
--- a/bin/pgsql-user
+++ b/bin/pgsql-user
@@ -1,12 +1,12 @@
 #!/bin/bash
 set -uo pipefail
 #==============================================================#
-# File      :   pg-db
-# Desc      :   Create database on postgres cluster
+# File      :   pgsql-user
+# Desc      :   Create PostgreSQL Business USer
 # Ctime     :   2021-07-15
 # Mtime     :   2022-12-28
-# Path      :   bin/pg-db
-# Deps      :   ansible-playbook, pgsql-db.yml
+# Path      :   bin/pgsql-user
+# Deps      :   ansible-playbook, pgsql-user.yml
 # Author    :   Ruohang Feng (rh@vonng.com)
 # License   :   AGPLv3
 #==============================================================#
@@ -18,8 +18,8 @@ PIGSTY_HOME=$(cd $(dirname ${APP_DIR}) && pwd)
 #--------------------------------------------------------------#
 # Usage
 #--------------------------------------------------------------#
-# bin/pg-db <cluster> <dbname>  # define database in inventory first
-# `app.children.<cluster>.vars.pg_databases`, entry with name=<dbname>
+# bin/pgsql-user <cls> <username>  # define user in inventory first
+# `app.children.<cls>.vars.pg_users`, entry with name=<username>
 
 
 #--------------------------------------------------------------#
@@ -35,27 +35,23 @@ function log_input() { printf "[${__CM} IN ${__CN}] ${__CM}$*\n=> ${__CN}"; }
 function log_hint()  { printf "${__CB}$*${__CN}\n"; }
 function log_line()  { printf "${__CM}[$*] ===========================================${__CN}\n"; }
 
-
-
 #--------------------------------------------------------------#
 # Param
 #--------------------------------------------------------------#
 PG_CLUSTER=${1-''}
-DBNAME=${2-''}
+USERNAME=${2-''}
 
 if [[ -z "${PG_CLUSTER}" ]]; then
     log_error "pg_cluster is empty"
     log_hint "Usage:"
-    log_hint "    bin/pg-db <cls> <dbname>"
+    log_hint "    bin/pgsql-user <cls> <username>"
     exit 1
 fi
-if [[ -z "${DBNAME}" ]]; then
-    log_error "dbname is empty"
+if [[ -z "${USERNAME}" ]]; then
+    log_error "username is empty"
+    log_warn "don't forget to define user in  all.children.${PG_CLUSTER}.vars.pg_users  first"
     log_hint "Usage:"
-    log_hint "    bin/pg-db <cls> <dbname>"
-
-    log_warn "don't forget to define database in  all.children.${PG_CLUSTER}.vars.pg_databases  first"
-    log_warn "if database have owner, make sure the user already exists, or create it with pg-user first"
+    log_hint "    bin/pgsql-user <cls> <username>"
     exit 2
 fi
 
@@ -64,17 +60,17 @@ fi
 # Execute
 #--------------------------------------------------------------#
 log_line "EXECUTE"
-log_warn "create pg database '${DBNAME}' on '${PG_CLUSTER}'"
-log_hint "$ ./pgsql-db.yml -l ${PG_CLUSTER} -e dbname=${DBNAME}"
-"${PIGSTY_HOME}/pgsql-db.yml" -l "${PG_CLUSTER}" -e dbname="${DBNAME}"
-RETURN_CODE=$?
+log_warn "create pgsql user '${USERNAME}' on '${PG_CLUSTER}'"
+log_hint "$ ./pgsql-user.yml -l ${PG_CLUSTER} -e username=${USERNAME}"
 
-log_line "SUMMARY"
-if [[ ${RETURN_CODE} -eq 0 ]]; then
-  log_info "create pg database ${DBNAME} on '${PG_CLUSTER}' complete"
-  log_hint "check pgurl: postgres://${PG_CLUSTER}/${DBNAME}"
-  exit 0
-else
-  log_error "fail to create pg database ${DBNAME} on '${PG_CLUSTER}'"
+"${PIGSTY_HOME}/pgsql-user.yml" -l "${PG_CLUSTER}" -e username="${USERNAME}"
+
+if [[ $? -ne 0 ]]; then
+  log_line "FAILURE"
+  log_error "fail to create pgsql user on '${PG_CLUSTER}'"
   exit 3
 fi
+log_line "SUMMARY"
+log_info "create pgsql user ${DBNAME} on '${PG_CLUSTER}' complete"
+log_hint "check pgurl: postgres://${USERNAME}:<PASSWORD>@${PG_CLUSTER}/postgres"
+exit 0
