add debian/ubuntu stub in bootstrap logic

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -3,12 +3,12 @@
 # File      :   bootstrap
 # Desc      :   setup local repo & install boot utils
 # Ctime     :   2022-10-16
-# Mtime     :   2023-08-19
+# Mtime     :   2023-09-29
 # Path      :   bootstrap
 # Author    :   Ruohang Feng (rh@vonng.com)
 # License   :   AGPLv3
 #==============================================================#
-VERSION=v2.4.1
+PIGSTY_VERSION=v2.4.1
 
 
 #--------------------------------------------------------------#
@@ -31,6 +31,9 @@ VERSION=v2.4.1
 #  -y  --yes             : download pkg.tgz from internet, ask by default
 #  -n  --no              : do not download pkg.tgz from internet
 #--------------------------------------------------------------#
+REGION=""               # which mirror to use? (default|china)
+DOWNLOAD_PKG=ask        # download pkg.tgz ? (ask|yes|no, ask by default)
+PKG_PATH=/tmp/pkg.tgz   # which pkg to be used ? (/tmp/pkg.tgz by default)
 
 
 #--------------------------------------------------------------#
@@ -57,27 +60,6 @@ VERSION=v2.4.1
 #--------------------------------------------------------------#
 
 
-#----------------------------------------------#
-# Param
-#----------------------------------------------#
-REGION=""               # which mirror to use? (default|china|europe)
-DOWNLOAD_PKG=ask        # download pkg.tgz ? (ask|yes|no, ask by default)
-PKG_PATH=/tmp/pkg.tgz   # which pkg to be used ? (/tmp/pkg.tgz by default)
-PROG_NAME="$(basename $0)"
-PIGSTY_HOME="$(cd $(dirname $0) && pwd)"
-REPO_NAME=pigsty
-NGINX_HOME=/www
-REPO_DIR=${NGINX_HOME}/${REPO_NAME}
-OS_VERSION=${OS_VERSION-'7'}
-OS_VENDOR="RedHat"
-ARCH=$(uname -m)
-BASEURL="https://github.com/Vonng/pigsty/releases/download/${VERSION}"
-SRC_FILENAME="pigsty-${VERSION}.tgz"
-PKG_FILENAME="pigsty-pkg-${VERSION}.el${OS_VERSION}.x86_64.tgz"
-DEFAULT_SRC_URL="${BASEURL}/${SRC_FILENAME}"
-DEFAULT_PKG_URL="${BASEURL}/${PKG_FILENAME}"
-
-
 #--------------------------------------------------------------#
 # Utils
 #--------------------------------------------------------------#
@@ -90,6 +72,25 @@ function log_debug() { printf "[${__CB}HINT${__CN}] ${__CB}$*${__CN}\n"; }
 function log_input() { printf "[${__CM} IN ${__CN}] ${__CM}$*\n=> ${__CN}"; }
 function log_hint()  { printf "${__CB}$*${__CN}"; }
 ipv4_regexp='(([0-9]|[0-9]{2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[0-9]{2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])'
+
+
+#--------------------------------------------------------------#
+# Param
+#--------------------------------------------------------------#
+PROG_NAME="$(basename $0)"
+PROG_DIR="$(cd $(dirname $0) && pwd)"
+PIGSTY_HOME="${PROG_DIR}"
+REPO_NAME=pigsty
+NGINX_HOME=/www
+REPO_DIR=${NGINX_HOME}/${REPO_NAME}
+BIN_DIR=${PIGSTY_HOME}/files/bin
+
+# extract os vendor & version from /etc/os-release
+OS_VENDOR=""
+OS_VERSION=""
+OS_PACKAGE=""
+OS_MANAGER=""
+ARCH=$(uname -m)
 
 
 #----------------------------------------------#
@@ -108,14 +109,9 @@ function check_region(){
   if [ "${REGION}" == "" ]; then
     if behind_gfw; then
         REGION=china       # mainland china is behind GFW
-        BASEURL="https://get.pigsty.cc/${VERSION}"
     else
         REGION=default     # otherwise use default mirror
     fi
-    SRC_FILENAME="pigsty-${VERSION}.tgz"
-    PKG_FILENAME="pigsty-pkg-${VERSION}.el${OS_VERSION}.x86_64.tgz"
-    DEFAULT_SRC_URL="${BASEURL}/${SRC_FILENAME}"
-    DEFAULT_PKG_URL="${BASEURL}/${PKG_FILENAME}"
     log_info "region = ${REGION}"
   fi
 }
@@ -149,29 +145,62 @@ function check_machine(){
 }
 
 #----------------------------------------------#
+# os package manager (yum|apt|...)
+#----------------------------------------------#
+function check_package_manager(){
+    # get package / manager: rpm|deb and dnf|yum|apt|apt-get|zypper
+    if command -v dpkg >/dev/null 2>&1; then
+        OS_PACKAGE="deb"
+        if command -v apt >/dev/null 2>&1; then
+            OS_MANAGER="apt"
+        elif command -v apt-get >/dev/null 2>&1; then
+            OS_MANAGER="apt-get"
+        else
+            log_error "fail to determine os package manager for deb"
+            exit 4
+        fi
+    elif command -v rpm >/dev/null 2>&1; then
+        OS_PACKAGE="rpm"
+        if command -v dnf >/dev/null 2>&1; then
+            OS_MANAGER="dnf"
+        elif command -v yum >/dev/null 2>&1; then
+            OS_MANAGER="yum"
+        elif command -v zypper >/dev/null 2>&1; then
+            OS_MANAGER="zypper"
+        else
+            log_error "fail to determine os package manager for rpm"
+            exit 4
+        fi
+    else
+        log_error "fail to determine os package type"
+        exit 3
+    fi
+    log_info "package = ${OS_PACKAGE},${OS_MANAGER}"
+}
+
+
+#----------------------------------------------#
 # os release (Linux|Darwin etc..)
 #----------------------------------------------#
-function check_release(){
-    if [[ ! -f /etc/redhat-release ]]; then
-        log_error "release = unknown, /etc/redhat-release not exists"
-        log_error "pigsty works on RHEL and compatible distributions, use with caution, assume OS_VERSION=${OS_VERSION}"
-        OS_VENDOR="Unknown"
-        #exit 3
-    else
-        local full=`cat /etc/redhat-release | tr -dc '0-9.'`
-        local major=$(cat /etc/redhat-release | tr -dc '0-9.'|cut -d \. -f1)
-        local minor=$(cat /etc/redhat-release | tr -dc '0-9.'|cut -d \. -f2)
-        local asynchronous=$(cat /etc/redhat-release | tr -dc '0-9.'|cut -d \. -f3)
-        if [[ ${major} != "7" && ${major} != "8" && ${major} != "9"  ]]; then
-            log_error "release = ${full} ,  supported release: el7,el8,el9"
-            log_error "pigsty works on el 7,8,9, please use with caution!"
-            #exit 4
-        fi
-        OS_VERSION=${major}
-        log_info "release = ${full}"
-    fi
-    return 0
+function check_vendor_version(){
+  if [[ -f /etc/os-release ]]; then
+      . /etc/os-release
+      OS_VENDOR="$ID"
+      OS_VERSION="$VERSION_ID"
+      if [[ $VERSION_ID == *.* ]]; then
+          OS_VERSION=$(echo "$VERSION_ID" | cut -d. -f1)
+      else
+          OS_VERSION="${VERSION_ID}"
+      fi
+      log_info "vendor = ${OS_VENDOR} (${NAME})"
+      log_info "version = ${OS_VERSION} (${VERSION_ID})"
+      return 0
+  else
+      log_error "/etc/os-release file not found, unknown OS"
+      exit 5
+  fi
 }
+
 
 #----------------------------------------------#
 # sudo
@@ -187,6 +216,7 @@ function can_nopass_sudo(){
     return 1
 }
 
+# sudo is required to extract /www/pigsty
 function check_sudo(){
     local current_user=$(whoami)
     if can_nopass_sudo; then
@@ -200,17 +230,52 @@ function check_sudo(){
 }
 
 
-
 #----------------------------------------------#
 # check pkg.tgz exists (optionally download)
 #----------------------------------------------#
+# download file from url, if file already exists with same size, skip download
+function download_file(){
+  local data_url=$1
+  local data_file=$2
+
+  if [[ -f ${data_file} ]]; then
+    size=$(get_file_size ${data_file})
+    log_warn "data file exists, size: ${size} , path: ${data_file}"
+    curl_size=$(curl -sI ${data_url} | grep -i 'Content-Length' | awk '{print $2}' | tr -d '\r')
+    if [[ ${size} -eq ${curl_size} ]]; then
+      log_info "data url file has same size: ${curl_size} , skip downloading ${data_url}"
+      return 0
+    else
+      log_warn "data url file size ${curl_size} != local ${size}, downloading ${data_url}"
+      log_info "$ curl ${data_url} -o ${data_file}"
+      curl ${data_url} -o ${data_file}
+      return $?
+    fi
+  else
+    # log_info "download ${data_url} to ${data_file}"
+    log_info "$ curl ${data_url} -o ${data_file}"
+    curl ${data_url} -o ${data_file}
+    return $?
+  fi
+}
+
 function check_pkg(){
     local pkg_url=${1-''}                    # default package url from github
     local pkg_path=${2-${PKG_PATH}}          # default download path : /tmp/pkg.tgz
     local download_pkg=${3-${DOWNLOAD_PKG}}  # flag: if set, skip interactive asking
 
     if [[ ${pkg_url} == "" ]]; then
-        pkg_url="${BASEURL}/pigsty-pkg-${VERSION}.el${OS_VERSION}.x86_64.tgz"
+        baseurl="https://github.com/Vonng/pigsty/releases/download/${PIGSTY_VERSION}"
+        if [ "${REGION}" = "china" ]; then
+            baseurl="https://get.pigsty.cc/${PIGSTY_VERSION}"
+        fi
+
+        # TODO: debian/ubuntu naming
+        if [[ ${OS_PACKAGE} == "rpm" ]]; then
+            pkg_url="${baseurl}/pigsty-pkg-${PIGSTY_VERSION}.el${OS_VERSION}.x86_64.tgz"
+        elif [[ ${OS_PACKAGE} == "deb" ]]; then
+            pkg_url="${baseurl}/pigsty-pkg-${PIGSTY_VERSION}.ubuntu${OS_VERSION}.x86_64.tgz"
+        fi
     fi
 
     if [[ -f ${pkg_path} ]]; then
@@ -235,8 +300,7 @@ function check_pkg(){
         esac
     fi
     if [[ ${download_pkg} == "yes" ]]; then
-        log_info "download from Github ${pkg_url} to ${pkg_path}"
-        curl -fSL "${pkg_url}" -o "${pkg_path}"
+        download_file "${pkg_url}" "${pkg_path}"
         return $?
     else
         log_warn "cache = missing and skip download"
@@ -289,26 +353,26 @@ function add_el7_repo(){
     fi
     cat > "/tmp/el${releasever}.repo" <<-EOF
 [base-default]
-name = EL 7 Base \$releasever - \$basearch
-baseurl = ${baseurl}/centos/\$releasever/os/\$basearch/
+name = EL 7 Base 7 - \$basearch
+baseurl = ${baseurl}/centos/7/os/\$basearch/
 gpgcheck = 0
 enabled = 1
 skip_if_unavailable = 1
 [epel-default]
-name = EL 7 EPEL \$releasever - \$basearch
-baseurl = ${baseurl}/epel/\$releasever/\$basearch/
+name = EL 7 EPEL \7 - \$basearch
+baseurl = ${baseurl}/epel/7/\$basearch/
 gpgcheck = 0
 enabled = 1
 skip_if_unavailable = 1
 [extras-default]
-name = EL 7 Extras \$releasever - \$basearch
-baseurl = ${baseurl}/centos/\$releasever/extras/\$basearch/
+name = EL 7 Extras 7 - \$basearch
+baseurl = ${baseurl}/centos/7/extras/\$basearch/
 gpgcheck = 0
 enabled = 1
 skip_if_unavailable = 1
 [updates-default]
-name = EL 7 Updates \$releasever - \$basearch
-baseurl = ${baseurl}/centos/\$releasever/updates/\$basearch/
+name = EL 7 Updates 7 - \$basearch
+baseurl = ${baseurl}/centos/7/updates/\$basearch/
 gpgcheck = 0
 enabled = 1
 skip_if_unavailable = 1
@@ -361,44 +425,60 @@ EOF
 function add_local_repo(){
     local nginx_home=${1-${NGINX_HOME}}
     local repo_name=${2-${REPO_NAME}}
-    local releasever=OS_VERSION
-    cat > /tmp/pigsty-local.repo  <<-EOF
+
+    # add local repo for el compatible releases
+    if [[ ${OS_PACKAGE} == "rpm" ]]; then
+        local releasever=OS_VERSION
+        cat > /tmp/pigsty-local.repo  <<-EOF
 [pigsty-local]
 name=pigsty local \$releasever - \$basearch
 baseurl=file://${nginx_home}/${repo_name}/
 enabled=1
 gpgcheck=0
 EOF
-    if (( ${OS_VERSION} >= 8 )); then
-      echo "module_hotfixes=1" >> /tmp/pigsty-local.repo
+        if (( ${OS_VERSION} >= 8 )); then
+          echo "module_hotfixes=1" >> /tmp/pigsty-local.repo
+        fi
+        sudo mkdir -p /etc/yum.repos.d/backup
+        sudo mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/ 2> /dev/null || true
+        sudo mv -f /tmp/pigsty-local.repo /etc/yum.repos.d/pigsty-local.repo
     fi
-    sudo mkdir -p /etc/yum.repos.d/backup
-    sudo mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/ 2> /dev/null || true
-    sudo mv -f /tmp/pigsty-local.repo /etc/yum.repos.d/pigsty-local.repo
+
+    # TODO: add deb local repo
 }
 
 function check_repo_file(){
     local repo_name=${1-${REPO_NAME}}
     local nginx_home=${2-${NGINX_HOME}}
     local repo_file=/etc/yum.repos.d/${repo_name}-local.repo
+
+    # if repo exists, add local repo file, other wise add upstream repo
     if [[ ! -f ${nginx_home}/${repo_name}/repo_complete ]]; then
-        if [[ ${OS_VENDOR} == "RedHat" ]]; then
+
+        if [[ ${OS_PACKAGE} == "rpm" ]]; then
             if [[ $OS_VERSION == "7" ]]; then
-                add_el7_repo ${REGION}
+                add_el7_repo "${REGION}"
             elif [[ $OS_VERSION == "8" ||  $OS_VERSION == "9" ]]; then
-                add_el89_repo ${REGION}
+                add_el89_repo "${REGION}"
             fi
             log_warn "repo file = add el${OS_VERSION}.${ARCH} upstream"
             return 0
         fi
+
     else
         add_local_repo
         log_info "repo file = use ${repo_file}"
     fi
-    sudo yum clean all -q
-    sudo yum makecache -q
+
+    if [[ ${OS_PACKAGE} == "rpm" ]]; then
+        sudo yum clean all -q
+        sudo yum makecache -q
+    fi
+    # TODO: remake deb cache
+
     log_info "repo cache = created"
 }
+
 
 #----------------------------------------------#
 # check utils
@@ -409,7 +489,8 @@ function check_utils(){
     local nginx_home=${2-${NGINX_HOME}}
     local repo_file=/etc/yum.repos.d/${repo_name}-local.repo
 
-    if [[ $OS_VENDOR == "RedHat" ]]; then
+    # install el utils
+    if [[ ${OS_PACKAGE} == "rpm" ]]; then
         if [[ $OS_VERSION == "7" ]]; then
             log_info "install el7 utils"
             sudo yum install -y createrepo_c unzip wget yum-utils sshpass
@@ -423,12 +504,15 @@ function check_utils(){
             sudo dnf install -y createrepo_c unzip wget dnf-utils sshpass modulemd-tools
             sudo dnf install -y ansible python3.11-jmespath
         fi
-    else
-        log_warn "try install el utils"
-        sudo yum install -y createrepo_c unzip wget sshpass ansible
+        # restore backup repo
+        sudo cp -f /etc/yum.repos.d/backup/*.repo /etc/yum.repos.d/ 2> /dev/null || true
     fi
-    # restore backup repo ?
-    sudo cp -f /etc/yum.repos.d/backup/*.repo /etc/yum.repos.d/ 2> /dev/null || true
+
+    # TODO: install deb utils
+    if [[ ${OS_PACKAGE} == "deb" ]]; then
+        log_warn "install deb utils not implemented yet"
+        sudo apt install -y ansible unzip wget reprepro sshpass
+    fi
 
     # check ansible is installed
     if command -v ansible-playbook >/dev/null ; then
@@ -461,16 +545,17 @@ function main(){
         shift
     done
 
-    log_hint "bootstrap pigsty ${VERSION} begin\n"
-    check_region     # region        = default
-    check_kernel     # kernel        = Linux
-    check_machine    # machine       = x86_64
-    check_release    # release       = CentOS 7|8|9
-    check_sudo       # current_user  = NOPASSWD sudo
-    check_pkg        # check offline installation package exists (INTERACTIVE: ask for download confirmation)
-    check_repo       # create repo from pkg.tgz if exists
-    check_repo_file  # create local file repo file if repo exists
-    check_utils      # check ansible sshpass and other utils installed
+    log_hint "bootstrap pigsty ${PIGSTY_VERSION} begin\n"
+    check_region          # region        = default
+    check_kernel          # kernel        = Linux
+    check_machine         # machine       = x86_64
+    check_package_manager # package = rpm|deb, manager = dnf|yum|zypper|apt|apt-get
+    check_vendor_version  # release       = centos, version = 7,8,9...
+    check_sudo            # current_user  = NOPASSWD sudo
+    check_pkg             # check offline installation package exists (INTERACTIVE: ask for download confirmation)
+    check_repo            # create repo from pkg.tgz if exists
+    check_repo_file       # create local file repo file if repo exists
+    check_utils           # check ansible sshpass and other utils installed
     log_info "boostrap pigsty complete"
     log_hint "proceed with ./configure\n"
 }
