refactor pigsty config director fhs

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -3,7 +3,7 @@
 # File      :   bootstrap
 # Desc      :   setup local repo & install boot utils
 # Ctime     :   2022-10-16
-# Mtime     :   2024-07-05
+# Mtime     :   2024-08-03
 # Path      :   bootstrap
 # Author    :   Ruohang Feng (rh@vonng.com)
 # License   :   AGPLv3
@@ -14,25 +14,20 @@ PIGSTY_VERSION=v2.8.0
 #--------------------------------------------------------------#
 # Usage
 #--------------------------------------------------------------#
-#  boostrap [-p <path>] [-y|--yes] [-n|--no]
+#  boostrap [-r <region>] [-p <path>] [-k|--keep]
 #
 #  ./boostrap
 #     [-r|--region <region]   [default,china,europe]
 #     [-p|--path <path>]      specify another offline pkg path
-#     [-y|--yes]              download offline pkg without asking
-#     [-n|--no]               do not download offline pkg.tgz
-#
-# if neither `-y` or `-n` is specified, Pigsty will ask for
-# downloading `pkg.tgz` from the Internet during `bootstrap`
+#     [-k|--keep]             keep existing upstream repo during bootstrap
 #--------------------------------------------------------------#
 # args
 #  -r  --region <region> : mirror region to use (default|china|europe)
 #  -p  --path   <path>   : offline packages path, /tmp/pkg.tgz by default
-#  -y  --yes             : download pkg.tgz from internet, ask by default
-#  -n  --no              : do not download pkg.tgz from internet
+#  -k  --keep            : keep upstream repo during bootstrap?
 #--------------------------------------------------------------#
 REGION=""               # which mirror to use? (default|china)
-DOWNLOAD_PKG="no"       # download pkg.tgz ? (ask|yes|no, no by default)
+REMOVE_REPO="yes"       # keep existing upstream repo file?
 PKG_PATH=/tmp/pkg.tgz   # which pkg to be used ? (/tmp/pkg.tgz by default)
 
 
@@ -41,17 +36,17 @@ PKG_PATH=/tmp/pkg.tgz   # which pkg to be used ? (/tmp/pkg.tgz by default)
 #--------------------------------------------------------------#
 # This script make sure two things:
 #    1. ansible is installed
-#    2. local repo is prepared
+#    2. local repo is prepared, if /tmp/pkg.tgz exists
 # It perform following tasks:
 # 1. check preconditions
-# 2. check local repo exists ?
-#    Y -> create /etc/yum.repos.d/pigsty-local.repo
-#    N -> Download from Internet? Y -> Download from Github / CDN and add local repo file
-#                                 N -> Add basic os upstream repo manually ?
-#                                         Y -> add according to region / releasever
-#                                         N -> leave it to user
-#  after step 2, we have yum repo available. Local > Download > Upstream > User Provide
 #
+# 2. check local repo exists ?
+#    Y -> Extract and use local offline pkg repo
+#    N -> Internet access available ?
+#        |- [Y] -> add internet upstream repo (optional keeping existing repo)
+#        |- [N] -> always keep existing repo, and leave it to user to install
+#  after step 2, we have software repo available: Local > Internet > Existing
+
 # 3. install boot utils from available repo
 #     nginx,wget,sshpass,createrepo_c,yum-utils
 #     dnf-utils,modulemd-tools
@@ -106,6 +101,14 @@ function behind_gfw() {
         return 1
     fi
     return 0
+}
+
+function check_internet() {
+  if ping -c 1 -W 1 1.1.1.1 >/dev/null 2>&1; then
+    return 0
+  else
+    return 1
+  fi
 }
 
 function check_region(){
@@ -235,95 +238,45 @@ function check_sudo(){
 
 
 #----------------------------------------------#
-# check pkg.tgz exists (optionally download)
+# ssh
 #----------------------------------------------#
-# download file from url, if file already exists with same size, skip download
-function download_file(){
-  local data_url=$1
-  local data_file=$2
+# One MUST have nopass to localhost with same user
+# configure can fix that for you (via ssh-keygen)
 
-  if [[ -f ${data_file} ]]; then
-    size=$(get_file_size ${data_file})
-    log_warn "data file exists, size: ${size} , path: ${data_file}"
-    curl_size=$(curl -sI ${data_url} | grep -i 'Content-Length' | awk '{print $2}' | tr -d '\r')
-    if [[ ${size} -eq ${curl_size} ]]; then
-      log_info "data url file has same size: ${curl_size} , skip downloading ${data_url}"
-      return 0
+function can_nopass_ssh(){
+    local current_user=$(whoami)
+    local user=${1-${current_user}}
+    local ipaddr=${2-'127.0.0.1'}
+    if ssh -oBatchMode=yes -o "StrictHostKeyChecking no" ${user}@${ipaddr} 'ls' 1>/dev/null 2>/dev/null; then
+        return 0
     else
-      log_warn "data url file size ${curl_size} != local ${size}, downloading ${data_url}"
-      log_info "$ curl ${data_url} -o ${data_file}"
-      curl -L ${data_url} -o ${data_file}
-      return $?
+        return 1
     fi
-  else
-    # log_info "download ${data_url} to ${data_file}"
-    log_info "$ curl ${data_url} -o ${data_file}"
-    curl -L ${data_url} -o ${data_file}
-    return $?
-  fi
 }
 
-function check_pkg(){
-    local pkg_url=${1-''}                    # default package url from github
-    local pkg_path=${2-${PKG_PATH}}          # default download path : /tmp/pkg.tgz
-    local download_pkg=${3-${DOWNLOAD_PKG}}  # flag: if set, skip interactive asking
-
-    # build pigsty pkg download url
-    if [[ ${pkg_url} == "" ]]; then
-        baseurl="https://github.com/Vonng/pigsty/releases/download/${PIGSTY_VERSION}"
-        if [ "${REGION}" = "china" ]; then
-            baseurl="https://get.pigsty.cc/${PIGSTY_VERSION}"
-        fi
-        if [[ ${OS_PACKAGE} == "rpm" ]]; then
-            pkg_url="${baseurl}/pigsty-pkg-${PIGSTY_VERSION}.el${OS_VERSION}.x86_64.tgz"
-        elif [[ ${OS_PACKAGE} == "deb" ]]; then
-            pkg_url="${baseurl}/pigsty-pkg-${PIGSTY_VERSION}.${OS_VENDOR}${OS_VERSION}.x86_64.tgz"
-        fi
+function fix_nopass_ssh(){
+    [[ ! -d ~/.ssh ]] && mkdir -p ~/.ssh && chmod 0700 ~/.ssh;                      # make sure ssh dir exists
+    [[ ! -f ~/.ssh/id_rsa ]] && ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N '' # gen ssh key if not exists
+    touch ~/.ssh/authorized_keys && chmod 0700 ~/.ssh/{authorized_keys,id_rsa}
+    local publicKey=$(cat ~/.ssh/id_rsa.pub 2>/dev/null)
+    if ! grep -q "${publicKey}" ~/.ssh/authorized_keys; then
+        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
     fi
+    return $(can_nopass_ssh)
+}
 
-    if [[ -f ${pkg_path} ]]; then
-        # TODO: checksum validate (but we will use 400MB sanity size check instead)
-        if (($(stat -c%s ${pkg_path})>409600000)); then
-            log_info "cache = ${pkg_path} exists"
-            return 0
-        else
-            log_warn "cache = ${pkg_path} exists but invalid"
-            rm -rf ${pkg_path}
-        fi
+function check_ssh(){
+    if can_nopass_ssh ; then
+        log_info "ssh = $(whoami)@127.0.0.1 ok"
+        return 0
     fi
-
-    # EL 8, Debian 12, Ubuntu 22 has official offline packages!
-    if [[ ${OS_PACKAGE} == "rpm" && ${OS_VERSION} == "8" ]]; then
-        log_info "EL 8.9 has pre-packed offline package available:"
-        log_hint "       ${pkg_url}\n"
-    elif [[ ${OS_PACKAGE} == "deb" && ${OS_CODENAME} == "jammy" ]]; then
-        log_info "Ubuntu 22.04 jammy has pre-packed offline package available:"
-        log_hint "       ${pkg_url}\n"
-    elif [[ ${OS_PACKAGE} == "deb" && ${OS_CODENAME} == "bookworm" ]]; then
-        log_info "Debian 12 bookworm has pre-packed offline package available:"
-        log_hint "       ${pkg_url}\n"
+    if fix_nopass_ssh; then
+        log_warn "ssh = $(whoami)@127.0.0.1 fixed"
+        return 0
     else
-        log_warn "${OS_VENDOR} ${OS_VERSION} ${OS_CODENAME} does not have corresponding offline package, use online install"
-        download_pkg="no"
+        log_warn "ssh = $(whoami)@127.0.0.1 failed"
+        # exit 6   # we don't exit here , just a configure process
     fi
-
-    # ask for confirmation if in interactive mode (and download is not specified)
-    if [[ ${download_pkg} == "ask" ]]; then
-        log_input "offline package not exist on /tmp/pkg.tgz, download? (y/n):"
-        read -r
-        local reply=$(echo "$REPLY" | tr '[:upper:]' '[:lower:]')
-        case "${reply}" in
-            y|yes|ok|true|aye|on) download_pkg=yes ;;
-            n|no|false|nay|off)   download_pkg=no  ;;
-        esac
-    fi
-    if [[ ${download_pkg} == "yes" ]]; then
-        download_file "${pkg_url}" "${pkg_path}"
-        return $?
-    else
-        log_warn "cache = missing and skip download"
-    fi
-    return 0
 }
 
 
@@ -336,14 +289,27 @@ function check_repo(){
     local repo_dir=${2-${REPO_DIR}}         # default repo directory: /www/pigsty
     local nginx_home=$(dirname ${repo_dir})
     local repo_name=$(basename ${repo_dir})
+
+    # if there's a repo with repo_complete flag, it means repo is ready, skip
     if [[ -f ${repo_dir}/repo_complete ]]; then
         log_info "repo = ${repo_dir} ok"
         return 0
     fi
+
+    # otherwise, if there's no /tmp/pkg.tgz, we can do nothing with repo, skip
     if [[ ! -f ${pkg_path} ]]; then
-        log_warn "repo = skip (${pkg_path} not exists)"
         return 0
+    else # if the /tmp/pkg.tgz exists, but looks suspicious, remove it
+        if (($(stat -c%s ${pkg_path})>409600000)); then
+            log_info "cache = ${pkg_path} exists"
+        else
+            log_warn "cache = ${pkg_path} exists but invalid"
+            rm -rf ${pkg_path}
+            return 0
+        fi
     fi
+
+    # extract /tmp/pkg.tgz to /www/pigsty
     sudo mkdir -p ${nginx_home}
     if [[ -d ${repo_dir} ]]; then
         log_warn "repo = invalid, remove"
@@ -389,7 +355,6 @@ baseurl = https://mirrors.aliyun.com/epel/7/$basearch/
 gpgcheck = 0
 enabled = 1
 EOF
-
     else
       cat > "/tmp/el${releasever}.repo" <<-EOF
 [base]
@@ -413,10 +378,9 @@ baseurl = http://download.fedoraproject.org/pub/epel/7/x86_64/
 gpgcheck = 0
 enabled = 1
 EOF
-
     fi
 
-    # el7's existing repo may not working anymore after EOL
+    # el7's existing repo may not working any more after EOL
     sudo mkdir -p /etc/yum.repos.d/backup
     sudo mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/ 2> /dev/null || true
     sudo mv -f "/tmp/el${releasever}.repo" "/etc/yum.repos.d/el${releasever}.repo"
@@ -517,18 +481,12 @@ EOF
         if (( ${OS_VERSION} >= 8 )); then
           echo "module_hotfixes=1" >> /tmp/pigsty-local.repo
         fi
-        sudo mkdir -p /etc/yum.repos.d/backup
-        sudo mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/ 2> /dev/null || true
-        sudo mv -f /tmp/pigsty-local.repo /etc/yum.repos.d/pigsty-local.repo
         log_info "repo file = use /etc/yum.repos.d/pigsty-local.repo"
         return 0
+        sudo mv -f /tmp/pigsty-local.repo /etc/yum.repos.d/pigsty-local.repo
     fi
 
     if [[ ${OS_PACKAGE} == "deb" ]]; then
-        sudo mkdir -p /etc/apt/backup
-        sudo mv -f /etc/apt/sources.list.d/* /etc/apt/backup/ 2> /dev/null || true
-        sudo mv -f /etc/apt/sources.list     /etc/apt/backup/ 2> /dev/null || true
-        sudo rm -rf /tmp/pigsty-local.list;
         echo "deb [trusted=yes] file:${nginx_home}/${repo_name}/ ./" > /tmp/pigsty-local.list
         sudo mv /tmp/pigsty-local.list /etc/apt/sources.list.d/pigsty-local.list
         log_info "repo file = use /etc/apt/sources.list.d/pigsty-local.list"
@@ -539,42 +497,87 @@ EOF
     return 1
 }
 
-function check_repo_file(){
-    local repo_name=${1-${REPO_NAME}}
-    local nginx_home=${2-${NGINX_HOME}}
-    local repo_flag=${nginx_home}/${repo_name}/repo_complete
 
-    # if repo exists, add local repo file, other wise add upstream repo
-    if [[ -f ${repo_flag} ]]; then
-        add_local_repo
-    else
+function remove_existing_repo(){
+    if [[ ${REMOVE_REPO} == "yes" ]]; then
         if [[ ${OS_PACKAGE} == "rpm" ]]; then
-            if [[ $OS_VERSION == "7" ]]; then
-                add_el7_repo "${REGION}"
-            elif [[ $OS_VERSION == "8" ||  $OS_VERSION == "9" ]]; then
-                add_el89_repo "${REGION}"
-            fi
-            log_info "repo file = add el${OS_VERSION}.${ARCH} ${REGION} upstream"
-        elif [[ ${OS_PACKAGE} == "deb" ]]; then
-            if [[ ${OS_VENDOR} == "ubuntu" ]]; then
-                add_ubuntu_repo "${REGION}"
-            elif [[ ${OS_VENDOR} == "debian" ]]; then
-                add_debian_repo "${REGION}"
-            fi
-            log_info "repo file = add ${OS_VENDOR} ${OS_CODENAME} ${REGION} upstream"
+            log_warn "old repos = moved to /etc/yum.repos.d/backup"
+            sudo mkdir -p /etc/yum.repos.d/backup
+            sudo mv -f /etc/yum.repos.d/*.repo /etc/yum.repos.d/backup/ 2> /dev/null || true
+        fi
+        if [[ ${OS_PACKAGE} == "deb" ]]; then
+            log_warn "old repos = moved to /etc/apt/backup"
+            sudo mkdir -p /etc/apt/backup
+            sudo mv -f /etc/apt/sources.list.d/* /etc/apt/backup/ 2> /dev/null || true
+            sudo mv -f /etc/apt/sources.list     /etc/apt/backup/ 2> /dev/null || true
+            sudo rm -rf /tmp/pigsty-local.list;
         fi
     fi
+}
 
+function restore_backup_repo(){
+    if [[ ${OS_PACKAGE} == "rpm" ]]; then
+        sudo cp -f /etc/yum.repos.d/backup/*.repo /etc/yum.repos.d/ 2> /dev/null || true
+    fi
+    if [[ ${OS_PACKAGE} == "deb" ]]; then
+        if [[ -f /etc/apt/backup/sources.list ]]; then
+            sudo mv -f /etc/apt/backup/sources.list /etc/apt/sources.list 2> /dev/null || true
+        fi
+        sudo mv -f /etc/apt/backup/* /etc/apt/sources.list.d/ 2> /dev/null || true
+    fi
+}
+
+
+function add_upstream_repo(){
+    if [[ ${OS_PACKAGE} == "rpm" ]]; then
+        if [[ $OS_VERSION == "7" ]]; then
+            add_el7_repo "${REGION}"
+        elif [[ $OS_VERSION == "8" ||  $OS_VERSION == "9" ]]; then
+            add_el89_repo "${REGION}"
+        fi
+        log_info "repo file = add el${OS_VERSION}.${ARCH} ${REGION} upstream"
+    elif [[ ${OS_PACKAGE} == "deb" ]]; then
+        if [[ ${OS_VENDOR} == "ubuntu" ]]; then
+            add_ubuntu_repo "${REGION}"
+        elif [[ ${OS_VENDOR} == "debian" ]]; then
+            add_debian_repo "${REGION}"
+        fi
+        log_info "repo file = add ${OS_VENDOR} ${OS_CODENAME} ${REGION} upstream"
+    fi
+}
+
+function make_repo_cache(){
     if [[ ${OS_PACKAGE} == "rpm" ]]; then
         log_warn "rpm cache = updating, may take a while"
         sudo yum clean all -q
-        sudo yum makecache -q
+        sudo yum makecache
     elif [[ ${OS_PACKAGE} == "deb" ]]; then
         log_warn "apt cache = updating, may take a while"
         sudo apt update
     fi
-
     log_info "repo cache = created"
+}
+
+
+#----------------------------------------------#
+# check_repo_file
+#----------------------------------------------#
+function check_repo_file(){
+    local repo_name=${1-${REPO_NAME}}
+    local nginx_home=${2-${NGINX_HOME}}
+    local repo_flag=${nginx_home}/${repo_name}/repo_complete
+    if [[ -f ${repo_flag} ]]; then
+        # if repo exists, remove or keep existing repo according to arg (-k|--keep)
+        remove_existing_repo
+        add_local_repo
+    else
+          if check_internet; then
+              # if there's internet access, add upstream repo file, and remove or keep existing repo according to arg (-k|--keep)
+              remove_existing_repo
+              add_upstream_repo
+          fi
+    fi
+    make_repo_cache
 }
 
 
@@ -602,18 +605,12 @@ function check_utils(){
             sudo dnf install -y createrepo_c unzip wget dnf-utils sshpass modulemd-tools
             sudo dnf install -y ansible python3-jmespath
         fi
-        # restore backup repo
-        sudo cp -f /etc/yum.repos.d/backup/*.repo /etc/yum.repos.d/ 2> /dev/null || true
     fi
 
     # install deb utils
     if [[ ${OS_PACKAGE} == "deb" ]]; then
         sudo apt install -y unzip wget sshpass acl
         sudo apt install -y ansible python3-jmespath
-        if [[ -f /etc/apt/backup/sources.list ]]; then
-            sudo mv -f /etc/apt/backup/sources.list /etc/apt/sources.list 2> /dev/null || true
-        fi
-        sudo mv -f /etc/apt/backup/* /etc/apt/sources.list.d/ 2> /dev/null || true
     fi
 
     # check ansible is installed
@@ -634,12 +631,11 @@ function main(){
     while [ $# -gt 0 ]; do
         case $1 in
             -h|--help)
-                echo './bootstrap [-r|--region <region>] [-p|--path <pkg>] [-y|--yes] [-n|--no]'
+                echo './bootstrap [-r|--region <region>] [-p|--path <pkg>] [-y|--yes]'
                 exit 0;;
             -r|--region) REGION="$2"   ; shift ;;
             -p|--path|--pkg) PKG_PATH="$2" ; shift ;;
-            -y|--yes) DOWNLOAD_PKG=yes  ;;
-            -n|--no)  DOWNLOAD_PKG=no   ;;
+            -k|--keep) REMOVE_REPO=no ;;
             (--) shift; break;;
             (-*) echo "$0: error - unrecognized option $1" 1>&2; exit 1;;
             (*) break;;
@@ -654,7 +650,7 @@ function main(){
     check_package_manager # package = rpm|deb, manager = dnf|yum|zypper|apt|apt-get
     check_vendor_version  # release       = rocky, version = 7,8,9...
     check_sudo            # current_user  = NOPASSWD sudo
-    check_pkg             # check offline installation package exists (INTERACTIVE: ask for download confirmation)
+    check_ssh             # current_user  = NOPASSWD ssh
     check_repo            # create repo from pkg.tgz if exists
     check_repo_file       # create local file repo file if repo exists
     check_utils           # check ansible sshpass and other utils installed
diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,7 +3,7 @@
 # File      :   configure
 # Desc      :   generate pigsty.yml config according to env
 # Ctime     :   2021-05-17
-# Mtime     :   2024-05-18
+# Mtime     :   2024-08-03
 # Path      :   configure
 # Author    :   Ruohang Feng (rh@vonng.com)
 # License   :   AGPLv3
@@ -16,21 +16,20 @@ PIGSTY_VERSION=v2.8.0
 #--------------------------------------------------------------#
 # ./configure
 #     [-i|--ip <ip>]
-#     [-r|--region <region]   [default,china,europe]
-#     [-m|--mode <mode]       [el7,el8,el9,sec,citus,redis...]
+#     [-r|--region <region>   [default|china|europe]
+#     [-c|--conf <confname>   [meta|dual|trio|full|prod]
 #     [-n|--non-interactive]
 #     [-x|--proxy]
 #==============================================================#
 # args
 #  -i  --ip  <ip addr>    : set local primary ip address
-#  -m  --mode             : mode, (el7|el8|el9|ubuntu20|debian|...)
+#  -c  --conf             : conf, (el7|el8|el9|ubuntu20|debian|...)
 #  -n  --non-interactive  : flag, run as non-interactive mode
 #  -x  --proxy            : flag, setup proxy_env from environment
 #==============================================================#
 INTERACTIVE=true                  # run configure with interactive mode
-PRIMARY_IP=""                     # primary IP address (intranet, do not use public IP)
-MODE=""                           # default install mode (el7|el8|el9|demo|sec|citus|redis)
-SPEC=tiny                         # default postgres spec (tiny|mini|small|medium|large|huge)
+PRIMARY_IP=""                     # primary IP address (do not use public IP)
+MODE=""                           # config template (meta|dual|trio|full|prod)
 REGION=""                         # default region (default|china|europe)
 USE_PROXY=false                   # use global env http_proxy, https_proxy, all_proxy, no_proxy
 DEFAULT_NO_PROXY="localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/16,*.pigsty,*.aliyun.com,mirrors.*,mirror.*,*.myqcloud.com,*.tsinghua.edu.cn,*.fedoraproject.org"
@@ -198,7 +197,7 @@ function check_vendor_version(){
       else
           OS_VERSION="${VERSION_ID}"
       fi
-      log_info "vendor = ${OS_VENDOR} (${NAME})"
+      log_info "vendor  = ${OS_VENDOR} (${NAME})"
       log_info "version = ${OS_VERSION} (${VERSION_ID})"
       return 0
   else
@@ -229,7 +228,7 @@ function check_sudo(){
     else
         log_warn "sudo = ${current_user} missing nopasswd"
         log_warn "fix nopass sudo for '${current_user}' with sudo:"
-        log_hint "echo '%%${current_user} ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/${current_user}"
+        log_hint "echo '%%${current_user} ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/${current_user}\n"
         # exit 5   # we don't exit here , just a configure process
     fi
 }
@@ -252,24 +251,9 @@ function can_nopass_ssh(){
     fi
 }
 
-function fix_nopass_ssh(){
-    [[ ! -d ~/.ssh ]] && mkdir -p ~/.ssh && chmod 0700 ~/.ssh;                      # make sure ssh dir exists
-    [[ ! -f ~/.ssh/id_rsa ]] && ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N '' # gen ssh key if not exists
-    touch ~/.ssh/authorized_keys && chmod 0700 ~/.ssh/{authorized_keys,id_rsa}
-    local publicKey=$(cat ~/.ssh/id_rsa.pub 2>/dev/null)
-    if ! grep -q "${publicKey}" ~/.ssh/authorized_keys; then
-        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
-    fi
-    return $(can_nopass_ssh)
-}
-
 function check_ssh(){
     if can_nopass_ssh ; then
         log_info "ssh = $(whoami)@127.0.0.1 ok"
-        return 0
-    fi
-    if fix_nopass_ssh; then
-        log_warn "ssh = $(whoami)@127.0.0.1 fixed"
         return 0
     else
         log_warn "ssh = $(whoami)@127.0.0.1 failed"
@@ -328,8 +312,9 @@ function check_ipaddr(){
 
     local ipCount=$(get_ip_count)
     if ((ipCount<1)); then
-        log_error "primary_ip = probe failed"
-        exit 8
+        log_warn "primary_ip = probe failed, use 10.10.10.10"
+        PRIMARY_IP=10.10.10.10
+        return 0
     fi
     if ((ipCount==1)); then
         log_info "primary_ip = $(hostname --all-ip-addresses) (from probe)"
@@ -351,7 +336,7 @@ function check_ipaddr(){
     # ask for input if in interactive mode, abort on non-interactive mode
     if [[ ${interactive} != "true" ]]; then
         log_error "primary_ip = dilemma abort"
-        log_hint "HINT: specify ip with -i|--ip , or disable non-interactive mode"
+        log_hint "HINT: specify ip with -i|--ip , or disable non-interactive mode\n"
         exit 9
     fi
 
@@ -377,16 +362,16 @@ function check_ipaddr(){
 function check_admin(){
     local primary_ip=${1-${PRIMARY_IP}}
     local current_user=$(whoami)
-    if ssh -t -o "StrictHostKeyChecking no" ${primary_ip} 'sudo -n ls' 1>/dev/null 2>/dev/null; then
+    if ssh -t -o "StrictHostKeyChecking no" -o "ConnectTimeout=4" ${primary_ip} 'sudo -n ls' 1>/dev/null 2>/dev/null; then
         log_info "admin = ${current_user}@${primary_ip} ok"
     else
-        log_warn "admin = ${current_user}@${primary_ip} failed"
-        log_hint "check ${current_user} in sudoer, @${primary_ip} is ssh accessible"
-        # exit 10 # we don't exit here , just a configure process
+        log_error "admin = ${current_user}@${primary_ip} failed (nopass ssh sudo failed)"
+        log_hint "check ${current_user} in sudoer, @${primary_ip} is ssh accessible\n"
+        # exit 10  # we don't exit here , just a configure process
     fi
     # if using root, warning
     if [[ "${current_user}" == "root" ]]; then
-        log_warn "use root = not recommended, are you sure?"
+        log_warn "user = root is not recommended, sure?"
     fi
 }
 
@@ -406,19 +391,22 @@ function check_mode(){
     # use el by default, and adhoc template for el7, will be obsolete soon (2024)
     if [[ ${OS_PACKAGE} == "rpm" ]]; then
         if [[ "${OS_VERSION}" == "7" ]]; then
-            MODE=el7    # deprecated os support: el7
+            MODE=default/el7    # deprecated os support: el7
+            log_warn "mode = el7, CentOS 7.9 EOL @ 2024-06-30, deprecated, consider using el8 or el9 instead"
             return 0
         elif [[ "${OS_VERSION}" == "8" ]]; then
-            MODE=el8
+            MODE=default/el8
+            log_info "mode = el8"
             return 0
         elif [[ "${OS_VERSION}" == "9" ]]; then
-            MODE=el9
+            MODE=default/el9
+            log_info "mode = el9"
             return 0
         fi
 
         # fallback to el8 by default
-        log_warn "mode = ${OS_VENDOR} ${OS_VERSION} unknown, fallback to el8"
-        MODE=el8
+        log_warn "mode = ${OS_VENDOR} ${OS_VERSION} unknown, fallback to default/el8"
+        MODE=default/el8
         return 0
     fi
 
@@ -426,31 +414,36 @@ function check_mode(){
     if [[ ${OS_PACKAGE} == "deb" ]]; then
         if [[ "${OS_VENDOR}" == "debian" ]]; then
             if [[ "${OS_VERSION}" == "11" ]]; then
-                MODE=debian11
+                MODE=default/d11     # deprecated os support: debian11
+                log_warn "mode = d11 (debian11), EOL @ 2024-08-14, deprecated, consider using debian12 instead"
                 return 0
             elif [[ "${OS_VERSION}" == "12" ]]; then
-                MODE=debian12
+                MODE=default/d12
+                log_info "mode = d12 (debian12)"
                 return 0
             fi
-            MODE=debian12
-            log_warn "mode = ${OS_VENDOR} ${OS_VERSION} unknown, fallback to debian 12"
+            MODE=default/d12
+            log_warn "os = ${OS_VENDOR} ${OS_VERSION} unknown, fallback to debian 12"
             return 0
         elif [[ "${OS_VENDOR}" == "ubuntu" ]]; then
             if [[ "${OS_VERSION}" == "20" ]]; then
-                MODE=ubuntu20     # deprecated os support: ubuntu20
+                MODE=default/u20     # deprecated os support: ubuntu20
+                log_warn "mode = u20 (ubuntu20.04), EOL @ 2025-04-23, deprecated, consider using ubuntu22.04 instead"
                 return 0
             elif [[ "${OS_VERSION}" == "22" ]]; then
-                MODE=ubuntu22
+                MODE=default/u22
+                log_info "mode = u22 (ubuntu22.04)"
                 return 0
             fi
-            MODE=ubuntu22
-            log_warn "mode = ${OS_VENDOR} ${OS_VERSION} unknown, fallback to ubuntu 22"
+            MODE=default/u22
+            log_warn "os = ${OS_VENDOR} ${OS_VERSION} unknown, fallback to ubuntu 22"
             return 0
         fi
     fi
 
-    # fallback to full.yml
-    MODE=full
+    # if OS is not determined, fall backup to the generic conf/meta.yml
+    log_warn "mode = meta (fallback to generic config)"
+    MODE=meta
     return 0
 }
 
@@ -461,38 +454,48 @@ function check_mode(){
 #----------------------------------------------#
 function check_config(){
     local primary_ip=${1-${PRIMARY_IP}}
-    local mode=${2-${MODE}}                        # use files/pigsty/${mode}.yml as template
+    local mode=${2-${MODE}} # use files/pigsty/${mode}.yml as template
     local pigsty_home=${3-${PIGSTY_HOME}}
-    local sed_cmd1="s/10.10.10.10/${primary_ip}/g" # replace 10.10.10.10 with actual ip address
-    local config_src=${pigsty_home}/files/pigsty/${mode}.yml
-    local config_dst=${pigsty_home}/pigsty.yml
+    local config_src="${pigsty_home}/conf/${mode}.yml"
+    local config_dst="${pigsty_home}/pigsty.yml"
 
+    # panic if given config file not exists
     if [[ ! -f ${config_src} ]]; then
-        log_error "config mode = ${mode} not exists"
+        log_error "config = conf/${mode}.yml not exists"
         exit 11
     fi
+    cat "${config_src}" > "${config_dst}"
+
+    # copy target config, and replace IP placeholder for singleton templates
+    case "${mode}" in
+      meta|default*) # replace primary IP address for these config templates
+        sed -ie "s/10.10.10.10/${primary_ip}/g" "${config_dst}"
+        rm -rf "${config_dst}e"
+        ;;
+    esac
 
     # replace node_tune & pg_conf with tiny or oltp according to cpu count
     if (($(getconf _NPROCESSORS_ONLN)>=4)); then
-        local sed_cmd2="s/pg_conf: tiny.yml/pg_conf: oltp.yml/g"   # replace pg_conf to oltp mode
-        local sed_cmd3="s/node_tune: tiny/node_tune: oltp/g"       # replace node_tune to oltp mode
-        cat ${config_src} | sed -e "${sed_cmd1}" | sed -e "${sed_cmd2}" | sed -e "${sed_cmd3}" > ${config_dst}
-        log_info "config = ${mode} @ ${primary_ip} [tiny -> oltp]"
-    else
-        cat ${config_src} | sed -e "${sed_cmd1}"  > ${config_dst}
-        log_info "config = ${mode} @ ${primary_ip}"
+        sed -ie "s/pg_conf: tiny.yml/pg_conf: oltp.yml/g" "${config_dst}"
+        sed -ie "s/node_tune: tiny/node_tune: oltp/g"     "${config_dst}"
+        rm -rf "${config_dst}e"
     fi
 
+    # replace region if not default
+    if [[ ${REGION} != "default" ]]; then
+        sed -ie 's/    region: default/    region: '"${REGION}"'  /g' "${config_dst}"
+        rm -rf "${config_dst}e"
+    fi
+
+    # add proxy_env from current env
     if [[ "${USE_PROXY}" == "true" ]]; then
         local proxy_txt_ori="    proxy_env:"
         local proxy_txt="${proxy_txt_ori}"
-
         # build proxy_env config from non-empty environment variable
         [[ "${HTTP_PROXY}"  != "" ]] && proxy_txt="${proxy_txt}\n      http_proxy: \"${HTTP_PROXY}\""
         [[ "${HTTPS_PROXY}" != "" ]] && proxy_txt="${proxy_txt}\n      https_proxy: \"${HTTPS_PROXY}\""
         [[ "${ALL_PROXY}"   != "" ]] && proxy_txt="${proxy_txt}\n      all_proxy: \"${ALL_PROXY}\""
         [[ "${NO_PROXY}"    != "" ]] && proxy_txt="${proxy_txt}\n      no_proxy: \"${NO_PROXY}\""
-
         # remove existing proxy_env config and replace with the new one:
         if [[ $proxy_txt != "${proxy_txt_ori}" ]]; then
             sed -ie "/^\s*proxy_env:.*$/d" "${config_dst}"
@@ -500,14 +503,10 @@ function check_config(){
             sed -ie "/^\s*all_proxy:.*$/d" "${config_dst}"
             sed -ie "/^\s*no_proxy:.*$/d" "${config_dst}"
             sed -ie "s%^\(\s\{4\}region:.\+\)$%\1\n${proxy_txt}%g" "${config_dst}"
+            rm -rf "${config_dst}e"
         fi
     fi
-
-    if [[ ${REGION} != "default" ]]; then
-        local sed_cmd4='s/    region: default/    region: '"${REGION}"'  /g'
-        sed -ie "${sed_cmd4}" ${config_dst}
-        rm -rf "${config_dst}e" || true
-    fi
+    rm -rf "${config_dst}e"
     return 0
 }
 
@@ -535,11 +534,12 @@ function main(){
     while [ $# -gt 0 ]; do
         case $1 in
             -h|--help)
-                echo './configure [-n|--non-interactive] [-d|--download] [-i|--ip <ipaddr>] [-m|--mode <mode>] [-x|--proxy]'
+                echo './configure [-n|--non-interactive] [-i|--ip <ipaddr>] [-c|--conf <confname>] [-x|--proxy]'
                 exit 0;;
             -i|--ip) PRIMARY_IP="$2" ; shift;;
             -r|--region) REGION="$2" ; shift;;
             -m|--mode)     MODE="$2" ; shift;;
+            -c|--conf|--config) MODE="$2" ; shift;;
             -n|--non-interactive) INTERACTIVE=false ;;
             -x|--proxy) USE_PROXY=true ;;
             (--) shift; break;;
