refacotr: change log level from error to warn during configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -131,8 +131,8 @@ function check_kernel(){
         log_info "kernel = ${kernel_name}"
         return 0
     else
-        log_error "kernel = ${kernel_name}, not supported, Linux only"
-        exit 1
+        log_warn "kernel = ${kernel_name}, not supported, Linux only"
+        #exit 1
     fi
 }
 
@@ -145,8 +145,8 @@ function check_machine(){
         log_info "machine = ${machine_name}"
         return 0
     else
-        log_error "machine = ${machine_name}, not supported, x86_64 only"
-        exit 2
+        log_warn "machine = ${machine_name}, not supported, x86_64 only"
+        #exit 2
     fi
 }
 
@@ -202,8 +202,8 @@ function check_vendor_version(){
       log_info "version = ${OS_VERSION} (${VERSION_ID})"
       return 0
   else
-      log_error "/etc/os-release file not found, unknown OS"
-      exit 5
+      log_warn "/etc/os-release file not found, unknown OS"
+      #exit 5
   fi
 }
 
