allow using -v|--version during configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,7 +3,7 @@
 # File      :   configure
 # Desc      :   generate pigsty.yml config according to env
 # Ctime     :   2021-05-17
-# Mtime     :   2024-08-25
+# Mtime     :   2024-11-15
 # Path      :   configure
 # Author    :   Ruohang Feng (rh@vonng.com)
 # License   :   AGPLv3
@@ -17,6 +17,7 @@ PIGSTY_VERSION=v3.1.0
 #     [-i|--ip <ip>]
 #     [-r|--region <region>   [default|china|europe]
 #     [-c|--conf <confname>   [meta|dual|trio|full|prod]
+#     [-v|--version <pgver>   [17|16|15|14|13|12]
 #     [-n|--non-interactive]
 #     [-x|--proxy]
 #==============================================================#
@@ -29,6 +30,7 @@ PIGSTY_VERSION=v3.1.0
 INTERACTIVE=true                  # run configure with interactive mode
 PRIMARY_IP=""                     # primary IP address (do not use public IP)
 MODE=""                           # config template (meta|dual|trio|full|prod)
+PGVER=""                          # major pg version (17/16/15/14/13/12)
 REGION=""                         # default region (default|china|europe)
 USE_PROXY=false                   # use global env http_proxy, https_proxy, all_proxy, no_proxy
 DEFAULT_NO_PROXY="localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/16,*.pigsty,*.aliyun.com,mirrors.*,mirror.*,*.myqcloud.com,*.tsinghua.edu.cn,*.fedoraproject.org"
@@ -46,7 +48,7 @@ function log_debug() { printf "[${__CB}HINT${__CN}] ${__CB}$*${__CN}\n"; }
 function log_input() { printf "[${__CM} IN ${__CN}] ${__CM}$*\n=> ${__CN}"; }
 function log_hint()  { printf "${__CB}$*${__CN}"; }
 ipv4_regexp='(([0-9]|[0-9]{2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[0-9]{2}|1[0-9]{2}|2[0-4][0-9]|25[0-5])'
-
+VALID_VERSIONS="12 13 14 15 16 17 18"
 
 #--------------------------------------------------------------#
 # Param
@@ -90,6 +92,36 @@ function check_region(){
   fi
 }
 
+
+
+#----------------------------------------------#
+# postgres major version
+#----------------------------------------------#
+function check_version(){
+    local found="false"
+    if [ -z "$PGVER" ]; then
+        return 0
+    else
+        for version in ${VALID_VERSIONS}; do
+            if [[ "$PGVER" == "$version" ]]; then
+                found="true"
+                break
+            fi
+        done
+
+        if [[ "$found" != "true" ]]; then
+            log_error "invalid pg major version: ${PGVER}"
+            log_hint "valid pg version numbers: ${VALID_VERSIONS}"
+            # If version is explicitly given and invalid, exit
+            exit 1
+        else
+            log_info "pg_ver = ${PGVER}"
+        fi
+    fi
+}
+
+
+
 #----------------------------------------------#
 # proxy
 #----------------------------------------------#
@@ -126,10 +158,10 @@ function check_proxy(){
 function check_kernel(){
     local kernel_name=$(uname -s)
     if [[ "${kernel_name}" == "Linux" ]]; then
-        log_info "kernel = ${kernel_name}"
+        log_info "kernel  = ${kernel_name}"
         return 0
     else
-        log_warn "kernel = ${kernel_name}, not supported, Linux only"
+        log_warn "kernel  = ${kernel_name}, not supported, Linux only"
         #exit 1
     fi
 }
@@ -523,6 +555,28 @@ function check_config(){
             rm -rf "${config_dst}e"
         fi
     fi
+
+    # if PGVER is non-empty, upsert pg_version & repo_modules accordingly
+    if [[ -n "${PGVER}" && "${mode}" != "ivory" && "${mode}" != "mssql" && "${mode}" != "polar"  ]]; then
+        # upsert pg_version to given PGVER
+        if grep -q 'pg_version:' "${config_dst}"; then
+            sed -ie "s/pg_version:.*$/pg_version: ${PGVER}  # set by configure/g" "${config_dst}"
+        else
+            sed -ie '$i\    pg_version: '"${PGVER}  # set by configure" "${config_dst}"
+        fi
+        rm -rf "${config_dst}e"
+
+        # for non-17 EL distro, add module to repo_modules
+        if [[ "${PGVER}" != "17" && "${OS_PACKAGE}" == "rpm" ]]; then
+            if grep -q '    repo_modules:' "${config_dst}"; then
+                sed -ie 's/\(    repo_modules:\s*\S*\)/\1,pg'"${PGVER}"'/g' "${config_dst}"
+            else
+                log_warn "add repo_modules"
+                sed -ie '$i\    repo_modules: infra,node,pgsql,pg'"${PGVER} # pg${PGVER} module is added during configure" "${config_dst}"
+            fi
+        fi
+    fi
+
     rm -rf "${config_dst}e"
     return 0
 }
@@ -551,12 +605,13 @@ function main(){
     while [ $# -gt 0 ]; do
         case $1 in
             -h|--help)
-                echo './configure [-n|--non-interactive] [-i|--ip <ipaddr>] [-c|--conf <confname>] [-x|--proxy]'
+                echo './configure [-n|--non-interactive] [-i|--ip <ipaddr>] [-c|--conf <confname>] [-v|--version 17] [-x|--proxy]'
                 exit 0;;
             -i|--ip) PRIMARY_IP="$2" ; shift;;
             -r|--region) REGION="$2" ; shift;;
             -m|--mode)     MODE="$2" ; shift;;
             -c|--conf|--config) MODE="$2" ; shift;;
+            -v|--ver|--version) PGVER="$2" ; shift;;
             -n|--non-interactive) INTERACTIVE=false ;;
             -x|--proxy) USE_PROXY=true ;;
             (--) shift; break;;
@@ -569,6 +624,7 @@ function main(){
     log_hint "configure pigsty ${PIGSTY_VERSION} begin\n"
     # check
     check_region          # region        = default
+    check_version         # pg_ver        = 17
     check_kernel          # kernel        = Linux
     check_machine         # machine       = x86_64/aarch64
     check_package_manager # package = rpm|deb, manager = dnf|yum|zypper|apt|apt-get
